### ISSUE TITLE
Unexpected error: 'enclosing tree does not include tree'

### ISSUE THREAD

**Issue by intracer** [scalacenter/bloop#1015]
INFO  compiling projectname-test (282 scala sources)
INFO  ======= Position error
Enclosing tree [40442] does not include tree [40441]
INFO  == Enclosing tree [40442] of type TypeApply at [1618:1754]OurTestNameSpec.scala
INFO  
INFO  [L  38        ] #40442  [1618:1754]     TypeApply  // must not throwA[IllegalArgumentException]()
INFO  
INFO  == Enclosed tree [40441] of type Select at [1618:1761]OurTestNameSpec.scala
INFO  
INFO  [L  38        ] #40441  [1618:1761]     Select     // throwA[IllegalArgumentException]()
INFO  
INFO  
While validating #40802
INFO  [L   1        ] #40802  [0:3811]        PackageDef // xml
INFO  
Children:
INFO    [L   1 P#40802] #40183  [8:47]          Select     // xml
INFO    [L   3 P#40802] #40186  [51:80]         Import     // akka.actor.ActorSystem
INFO    [L   4 P#40802] #40193  [82:139]        Import     // our class name
INFO    [L   5 P#40802] #40203  [141:210]       Import     // our class name
INFO    [L   6 P#40802] #40210  [212:250]       Import     // our class name
INFO    [L   7 P#40802] #40218  [252:331]       Import     // our class name
INFO    [L   8 P#40802] #40226  [333:404]       Import     // our class name
INFO    [L   9 P#40802] #40232  [406:451]       Import     // our class name
INFO    [L  10 P#40802] #40236  [453:486]       Import     // com.typesafe.config.Config
INFO    [L  11 P#40802] #40240  [488:519]       Import     // org.junit.runner.RunWith
INFO    [L  12 P#40802] #40244  [521:551]       Import     // org.specs2.mock.Mockito
INFO    [L  13 P#40802] #40248  [553:592]       Import     // org.specs2.mutable.Specification
INFO    [L  14 P#40802] #40252  [594:630]       Import     // org.specs2.runner.JUnitRunner
INFO    [L  15 P#40802] #40255  [632:661]       Import     // scala.reflect.ClassTag
INFO    [L  18 P#40802] #40801  [697:3811]      ClassDef   // OurTestNameSpec extends Specification with Mockito with UnitTestSetUpHelper {
INFO  =======
scala.reflect.internal.Positions$ValidateException: Enclosing tree [40442] does not include tree [40441]
	at scala.reflect.internal.Positions$class.positionError$1(Positions.scala:102)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:124)INFO  time: compiled projectname-test in 13s

	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validatePositions(Positions.scala:147)
	at scala.reflect.internal.SymbolTable.validatePositions(SymbolTable.scala:16)
	at scala.tools.nsc.ast.parser.SyntaxAnalyzer$ParserPhase.apply(SyntaxAnalyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:458)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:425)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1609)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:148)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:123)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:252)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:121)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:94)
	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.compileSources$1(BloopHighLevelCompiler.scala:127)
	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$7(BloopHighLevelCompiler.scala:140)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$1(BloopHighLevelCompiler.scala:70)
	at bloop.tracing.BraveTracer.trace(BraveTracer.scala:31)
	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.timed$1(BloopHighLevelCompiler.scala:69)
	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$6(BloopHighLevelCompiler.scala:140)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by intracer** [comment]
[bloop.log](https://github.com/scalacenter/bloop/files/3508556/bloop.log)

**Comment by jvican** [comment]
Judging from the stack trace, this is most likely not a problem in bloop but scalac. There's nothing we can do to fix this. Also, next time you file a ticket in this repository make sure you file a ticker properly, formatting errors and describing the issue in detail. I have zero context to look into this.

**Comment by intracer** [comment]
> What Scala version are you using? 
2.11.12

you are right, -Yrangepos was present in .bloop/*.json, and after removing this option, this error disappered. Project still failed to compile, this time with no error messages.
