### ISSUE TITLE
Failure exporting sbt project with recursive sbt plugin?

### ISSUE THREAD

**Issue by neko-kai** [scalacenter/bloop#1018]
To reproduce execute:

```
git clone https://github.com/7mind/izumi.git
cd izumi
METALS_ENABLED=true sbt metalsEnable bloopInstall
```

(assuming `~/.sbt/1.0/plugins/metals.sbt` file exists, installed by Metals)

Got exceptions:

```
[success] Generated .bloop/root.json
[error] sbt.internal.util.Init$RuntimeUndefined: References to undefined settings at runtime.
[error] setting(ScopedKey(Scope(Select(ProjectRef(file:/Users/kai/src/izumi-r2/sbt/sbt-izumi-deps/,sbt-izumi-deps)), Select(ConfigKey(compile)), Zero, Zero),bloopGenerate)) at LinePosition((bloop.integrations.sbt.BloopDefaults.configSettings) SbtBloop.scala,159) referenced from ScopedKey(Scope(Select(ProjectRef(file:/Users/kai/src/izumi-r2/sbt/sbt-izumi-deps/,sbt-izumi-deps)), Select(ConfigKey(compile)), Zero, Zero),pluginData)
[error] 	at sbt.internal.util.Init.sbt$internal$util$Init$$handleUndefined(Settings.scala:693)
[error] 	at sbt.internal.util.Init$$anon$9.apply(Settings.scala:697)
[error] 	at sbt.internal.util.Init$$anon$9.apply(Settings.scala:697)
[error] 	at sbt.internal.util.$tilde$greater$$anon$7.apply(TypeFunctions.scala:61)
[error] 	at sbt.internal.util.$tilde$greater$$anon$7.apply(TypeFunctions.scala:61)
[error] 	at sbt.std.FullInstance$.$anonfun$flatten$2(TaskMacro.scala:70)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] sbt.internal.util.Init$RuntimeUndefined: References to undefined settings at runtime.
[error] setting(ScopedKey(Scope(Select(ProjectRef(file:/Users/kai/src/izumi-r2/sbt/sbt-izumi/,sbt-izumi)), Select(ConfigKey(compile)), Zero, Zero),bloopGenerate)) at LinePosition((bloop.integrations.sbt.BloopDefaults.configSettings) SbtBloop.scala,159) referenced from ScopedKey(Scope(Select(ProjectRef(file:/Users/kai/src/izumi-r2/sbt/sbt-izumi/,sbt-izumi)), Select(ConfigKey(compile)), Zero, Zero),pluginData)
[error] 	at sbt.internal.util.Init.sbt$internal$util$Init$$handleUndefined(Settings.scala:693)
[error] 	at sbt.internal.util.Init$$anon$9.apply(Settings.scala:697)
[error] 	at sbt.internal.util.Init$$anon$9.apply(Settings.scala:697)
[error] 	at sbt.internal.util.$tilde$greater$$anon$7.apply(TypeFunctions.scala:61)
[error] 	at sbt.internal.util.$tilde$greater$$anon$7.apply(TypeFunctions.scala:61)
[error] 	at sbt.std.FullInstance$.$anonfun$flatten$2(TaskMacro.scala:70)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (ProjectRef(uri("file:/Users/kai/src/izumi-r2/sbt/sbt-izumi-deps/"), "sbt-izumi-deps") / Compile / bloopGenerate) sbt.internal.util.Init$RuntimeUndefined: References to undefined settings at runtime.
[error] setting(ScopedKey(Scope(Select(ProjectRef(file:/Users/kai/src/izumi-r2/sbt/sbt-izumi-deps/,sbt-izumi-deps)), Select(ConfigKey(compile)), Zero, Zero),bloopGenerate)) at LinePosition((bloop.integrations.sbt.BloopDefaults.configSettings) SbtBloop.scala,159) referenced from ScopedKey(Scope(Select(ProjectRef(file:/Users/kai/src/izumi-r2/sbt/sbt-izumi-deps/,sbt-izumi-deps)), Select(ConfigKey(compile)), Zero, Zero),pluginData)
[error] (ProjectRef(uri("file:/Users/kai/src/izumi-r2/sbt/sbt-izumi/"), "sbt-izumi") / Compile / bloopGenerate) sbt.internal.util.Init$RuntimeUndefined: References to undefined settings at runtime.
[error] setting(ScopedKey(Scope(Select(ProjectRef(file:/Users/kai/src/izumi-r2/sbt/sbt-izumi/,sbt-izumi)), Select(ConfigKey(compile)), Zero, Zero),bloopGenerate)) at LinePosition((bloop.integrations.sbt.BloopDefaults.configSettings) SbtBloop.scala,159) referenced from ScopedKey(Scope(Select(ProjectRef(file:/Users/kai/src/izumi-r2/sbt/sbt-izumi/,sbt-izumi)), Select(ConfigKey(compile)), Zero, Zero),pluginData)
[error] Total time: 5 s, completed 21-Aug-2019 19:14:22
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

**Comment by jvican** [comment]
Thanks for reporting @neko-kai You're probably doing something funky in sbt. Bloop exports the bloop build just fine which in turn uses recursive sbt plugins too. I'm not even sure this error has a potential fix on the sbt side.

**Comment by neko-kai** [comment]
Well, replacing `RootProject` references with `unmanagedSources in Compile += ...` in `plugins.sbt` fixes that. Maybe the difference could be that [izumi](https://github.com/7mind/izumi) uses TWO plugins recursively?..

**Comment by jvican** [comment]
I don't know of any reason why two plugins would cause an error and one wouldn't, but in any case this does look like an upstream issue in sbt. I'm not a big fan of `RootProject` because it's not well supported and has many implementation issues internally in sbt, I'd recommend to avoid using it.
  
Given that it's a little bit of a niche use case and we know a workaround, let's close this ticket. If you have more questions feel free to chat here!
