### ISSUE TITLE
Annotation processors from Immutables.org breaks bloop

### ISSUE THREAD

**Issue by domdorn** [scalacenter/bloop#1024]
In my project I have two modules, one for my main code and one java module which contains classes that are using the immutables.org library. 

Bloop (in connection with SBT?) apparently has problems with compiler-processors..
```
org.immutables.value.internal.$processor$.$Processor threw com.sun.tools.javac.util.ClientCodeException: java.lang.IllegalArgumentException: Not supported: sbt.internal.inc.javac.WriteReportingJavaFileObject@6ed17334
  	at com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.isSameFile(ClientCodeWrapper.java:261)
  	at com.sun.tools.javac.processing.JavacFiler.checkFileReopening(JavacFiler.java:532)
  	at com.sun.tools.javac.processing.JavacFiler.createSourceOrClassFile(JavacFiler.java:404)
  	at com.sun.tools.javac.processing.JavacFiler.createSourceFile(JavacFiler.java:378)
  	at org.immutables.value.internal.$generator$.$Output$SourceFile.complete($Output.java:314)
  	at org.immutables.value.internal.$generator$.$Output$7.invoke($Output.java:178)
  	at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
  	at org.immutables.value.internal.$processor$.$Generator_Immutables._t0__generate($Generator_Immutables.java:20)
  	at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:19610)
  	at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:248)
  	at org.immutables.value.internal.$generator$.$AbstractGenerator.invoke($AbstractGenerator.java:57)
  	at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:74)
  	at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:87)
  	at org.immutables.processor.ProxyProcessor.process(ProxyProcessor.java:72)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at bloop.CompilerCache$BloopJavaCompiler.run(CompilerCache.scala:252)
  	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$11(AnalyzingJavaCompiler.scala:156)
  	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  	at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:234)
  	at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:146)
  	at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:73)
  	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$9(BloopHighLevelCompiler.scala:159)
  	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$1(BloopHighLevelCompiler.scala:70)
  	at bloop.tracing.BraveTracer.trace(BraveTracer.scala:31)
  	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.timed$1(BloopHighLevelCompiler.scala:69)
  	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$8(BloopHighLevelCompiler.scala:152)
  	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
  	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
  	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
  	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
  	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
  	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
  	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
  	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
  Caused by: java.lang.IllegalArgumentException: Not supported: sbt.internal.inc.javac.WriteReportingJavaFileObject@6ed17334
  	at com.sun.tools.javac.file.JavacFileManager.isSameFile(JavacFileManager.java:647)
  	at javax.tools.ForwardingJavaFileManager.isSameFile(ForwardingJavaFileManager.java:90)
  	at com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.isSameFile(ClientCodeWrapper.java:257)
  	... 44 more
time: compiled events in 1.03s
```

I'm using bloop through metals / vscode / sbt

**Comment by jvican** [comment]
Thanks for the bug report. Looks like https://github.com/scalacenter/bloop/issues/962 and https://github.com/scalacenter/bloop/issues/956. When they are fixed, we can look if there's anything else that needs to be fixed to support your project. Could you find a minimal reproduction case so that we can look at it at some point? Whenever you have it we can reopen the ticket.
