### ISSUE TITLE
Show better feedback if Java is not installed during scoop install

### ISSUE THREAD

**Issue by PAStheLoD** [scalacenter/bloop#1121]
Hello,

This might be out of scope, but I found it rather puzzling, and the error message not very helpful, so maybe others stumble into this too.

```
[...]
'python' (3.8.0) was installed successfully!
Installing 'bloop' (1.3.4) [64bit]
install.py (12,4 KB) [========================================================================================] 100%
Checking hash of install.py ... ok.
Running installer script...
Downloading Bloop's coursier version, this may take some seconds...
Traceback (most recent call last):
  File "C:\Users\Tibi\scoop\apps\bloop\1.3.4/install.py", line 273, in <module>
    coursier_bootstrap(BLOOP_SERVER_TARGET, "bloop.Server")
  File "C:\Users\Tibi\scoop\apps\bloop\1.3.4/install.py", line 246, in coursier_bootstrap
    check_call(["java"] + http + https + ["-jar", BLOOP_COURSIER_TARGET, "bootstrap", BLOOP_ARTIFACT,
  File "C:\Users\Tibi\scoop\apps\python\current\lib\subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Tibi\scoop\apps\python\current\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Tibi\scoop\apps\python\current\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Tibi\scoop\apps\python\current\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] <localized error message from windows :(>
Linking ~\scoop\apps\bloop\current => ~\scoop\apps\bloop\1.3.4
Creating shim for 'bloop'.
Can't shim 'bloop.cmd': File doesn't exist.
```

It'd be helpful to recommend `scoop bucket add java` and then something like `scoop install adopt13-hotspot`.

**Comment by jvican** [comment]
Thanks for reporting this! Won't have time to look into this, but I suggest you look into it after our next release. I'll be happy to provide pointers to contribute to the project and get this issue addressed.

**Comment by jvican** [comment]
@PAStheLoD I'm going to close this ticket since this is not likely to be worked on any time soon. If you have the time to do this, I'd appreciate if you can pick it up.
