### ISSUE TITLE
NPE on any action 

### ISSUE THREAD

**Issue by Dnomyar** [scalacenter/bloop#1143]
Hey folks,

I exported bloop files using `sbt bloopInstall`. That worked fine. 

I tried to run `bloop projects` but I got a NPE.

<details><summary>Click to show stacktrace</summary>
<p>

```scala
$ bloop projects
java.lang.NullPointerException
	at bloop.ScalaInstance.supportsHydra(ScalaInstance.scala:78)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1(Project.scala:137)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1$adapted(Project.scala:137)
	at scala.Option.map(Option.scala:230)
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:137)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at bloop.ScalaInstance.supportsHydra(ScalaInstance.scala:78)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1(Project.scala:137)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1$adapted(Project.scala:137)
	at scala.Option.map(Option.scala:230)
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:137)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at bloop.ScalaInstance.supportsHydra(ScalaInstance.scala:78)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1(Project.scala:137)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1$adapted(Project.scala:137)
	at scala.Option.map(Option.scala:230)
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:137)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at bloop.ScalaInstance.supportsHydra(ScalaInstance.scala:78)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1(Project.scala:137)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1$adapted(Project.scala:137)
	at scala.Option.map(Option.scala:230)
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:137)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at bloop.ScalaInstance.supportsHydra(ScalaInstance.scala:78)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1(Project.scala:137)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1$adapted(Project.scala:137)
	at scala.Option.map(Option.scala:230)
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:137)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at bloop.ScalaInstance.supportsHydra(ScalaInstance.scala:78)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1(Project.scala:137)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1$adapted(Project.scala:137)
	at scala.Option.map(Option.scala:230)
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:137)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at bloop.ScalaInstance.supportsHydra(ScalaInstance.scala:78)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1(Project.scala:137)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1$adapted(Project.scala:137)
	at scala.Option.map(Option.scala:230)
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:137)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at bloop.ScalaInstance.supportsHydra(ScalaInstance.scala:78)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1(Project.scala:137)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1$adapted(Project.scala:137)
	at scala.Option.map(Option.scala:230)
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:137)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at bloop.ScalaInstance.supportsHydra(ScalaInstance.scala:78)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1(Project.scala:137)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1$adapted(Project.scala:137)
	at scala.Option.map(Option.scala:230)
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:137)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
</p>
</details>

Do you have any idea why?

**Comment by Dnomyar** [comment]
Looks like the same problem than this issue https://github.com/scalacenter/bloop/issues/1142

**Comment by jvican** [comment]
Thanks for reporting, duple of #1142
