### ISSUE TITLE
References to undefined settings `compileIncremental`

### ISSUE THREAD

**Issue by tgodzik** [scalacenter/bloop#1158]
Managed to reproduce an issue that some of the users are having with sbt 0.13.18
```
lazy val commonSettings = Seq(
  scalaVersion := "2.11.12",
  scalacOptions ++= Seq(
    "-deprecation",
    "-unchecked",
    "-encoding", "UTF-8",
    "-Yclosure-elim",
    "-Yinline",
    "-Xverify",
    "-feature"
  )
)

lazy val jmh = project
  .settings(commonSettings: _*)
```

It seems `.settings` is removing `compileIncremental`

**Comment by tgodzik** [comment]
The log we are getting:
```
[info] Done updating.
INFO  References to undefined settings: 
INFO  
INFO    jmh/it:compileIncremental from jmh/it:bloopCompile ((bloop.integrations.sbt.Offloader) Offloader.scala:19)
INFO  
INFO    sbt-old/it:compileIncremental from sbt-old/it:bloopCompile ((bloop.integrations.sbt.Offloader) Offloader.scala:19)
INFO   
INFO  	at sbt.Init$class.Uninitialized(Settings.scala:270)
INFO  	at sbt.Def$.Uninitialized(Def.scala:10)
INFO  	at sbt.Init$class.delegate(Settings.scala:191)
INFO  	at sbt.Def$.delegate(Def.scala:10)
INFO  	at sbt.Init$class.compiled(Settings.scala:138)
INFO  	at sbt.Def$.compiled(Def.scala:10)
INFO  	at sbt.Init$class.make(Settings.scala:144)
INFO  	at sbt.Def$.make(Def.scala:10)
INFO  	at sbt.Load$$anonfun$8.apply(Load.scala:161)
INFO  	at sbt.Load$$anonfun$8.apply(Load.scala:156)
INFO  	at sbt.Load$.timed(Load.scala:1039)
INFO  	at sbt.Load$.apply(Load.scala:156)
INFO  	at sbt.Load$.defaultLoad(Load.scala:39)
INFO  	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:504)
INFO  	at sbt.BuiltinCommands$.doLoadProject(Main.scala:504)
INFO  	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:496)
INFO  	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:496)
INFO  	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
INFO  	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
INFO  	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
INFO  	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
INFO  	at sbt.Command$.process(Command.scala:93)
INFO  	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
INFO  	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
INFO  	at sbt.State$$anon$1.runCmd$1(State.scala:183)
INFO  	at sbt.State$$anon$1.process(State.scala:187)
INFO  	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
INFO  	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
INFO  	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
INFO  	at sbt.MainLoop$.next(MainLoop.scala:96)
INFO  	at sbt.MainLoop$.run(MainLoop.scala:89)
INFO  	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
INFO  	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
INFO  	at sbt.Using.apply(Using.scala:24)
INFO  	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
INFO  	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
INFO  	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
INFO  	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
INFO  	at sbt.StandardMain$.runManaged(Main.scala:61)
INFO  	at sbt.xMain.run(Main.scala:35)
INFO  	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
INFO  	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
INFO  	at xsbt.boot.Launch$.run(Launch.scala:109)
INFO  	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
INFO  	at xsbt.boot.Launch$.launch(Launch.scala:117)
INFO  	at xsbt.boot.Launch$.apply(Launch.scala:18)
INFO  	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
INFO  	at xsbt.boot.Boot$.main(Boot.scala:18)
INFO  	at xsbt.boot.Boot.main(Boot.scala)
INFO  [error] References to undefined settings: 
INFO  [error] 
INFO  [error]   jmh/it:compileIncremental from jmh/it:bloopCompile ((bloop.integrations.sbt.Offloader) Offloader.scala:19)
INFO  [error] 
INFO  [error]   sbt-old/it:compileIncremental from sbt-old/it:bloopCompile ((bloop.integrations.sbt.Offloader) Offloader.scala:19)
INFO  [error]  
INFO  [error] Use 'last' for the full log.
```

**Comment by tgodzik** [comment]
@jvican Does it make sense to change the Offloader.scala:19 to an empty List?
`val bloopCompileConfigSettings: Seq[Def.Setting[_]] = List()`
It does fix it for me on the test project.

**Comment by jvican** [comment]
Thanks for reporting! Hmmm, I think that would work, could you submit a PR with that fix and the test case? I'm happy we tracked this one down, sbt 0.13 has some scoping issues and it's desirable that we don't regress when we go enable compile offloading.
