### ISSUE TITLE
Bloop won't install via Scoop

### ISSUE THREAD

**Issue by Arthurm1** [scalacenter/bloop#1281]
Bloop v1.4.1 gives an error when installing on Windows using Scoop...

```
Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading C:\Users\ArthurM\scoop\apps\bloop\1.4.1:latest.release
  not found: C:\Users\ArthurM\.ivy2\local\C\Users\ArthurM\scoop\apps\bloop\1.4.1
  not found: https://repo1.maven.org/maven2/C/\Users\ArthurM\scoop\apps\bloop\1.4.1/maven-metadata.xml
        at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:325)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:273)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at coursier.Resolve$.validate(Resolve.scala:323)
        at coursier.Resolve.validate0$1(Resolve.scala:112)
        at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:156)
        at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Linking ~\scoop\apps\bloop\current => ~\scoop\apps\bloop\1.4.1
Creating shim for 'bloop'.
Can't shim 'bloop': File doesn't exist.
```

Coursier looks like it's merging 2 directory names together.  Trying to call it directly gives the same error (although I'm not sure if this is how `--channel` is supposed to be specified)...
```
coursier install --install-dir C:\Users\ArthurM\scoop\apps\bloop\1.4.1 --default-channels=false --channel C:\Users\ArthurM\scoop\apps\bloop\1.4.1\bloop-coursier.json bloop
```

It works if I remove channel info and run...
```
coursier install --install-dir C:\Users\ArthurM\scoop\apps\bloop\1.4.1 bloop
```
I'm using coursier 2.0.0-RC6-16

Also - the shim isn't setup. I think the `"bin": "bloop"` section in `bloop.json` should read `"bin": "bloop.bat"`

**Comment by Arthurm1** [comment]
Temporary workaround...

Uninstall Bloop if you have installed it...
`scoop uninstall bloop`

Add the Bloop bucket
`scoop bucket add bloop-stable https://github.com/scalacenter/scoop-bloop.git`

Edit the bucket file:  `%home%/scoop/buckets/bloop-stable/bloop.json` (or wherever you installed Scoop) to be...
```
{
  "version": "1.4.1",
  "url": "https://github.com/scalacenter/bloop/releases/download/v1.4.1/bloop-coursier.json",
  "hash": "sha256:2e6a873183e5e22712913bfdab1331d0a7792167c369fee5be0c83e27572fe12",
  "depends": "coursier",
  "bin": "bloop.bat",
  "env_add_path": "$dir",
  "env_set": {
    "BLOOP_HOME": "$dir",
    "BLOOP_IN_SCOOP": "true"
  },
  "installer": {
    "script": "coursier install --install-dir $dir bloop"
  }
}
```

install bloop:
`scoop install bloop`

**Comment by jvican** [comment]
Hey @Arthurm1 thanks for reporting! Would you mind opening a PR with those changes in scoop-bloop so that it can be consumed right away and following up to that change with a PR in bloop itself, so that the next release contains these changes?

**Comment by Arthurm1** [comment]
@jvican please merge scalacenter/scoop-bloop#7 if you're happy with it

**Comment by heksesang** [comment]
So, it seems to not like it when you start the directory path with a drive letter, and it seems to not like that the file is called `bloop-coursier.json`. When you specify to install the app `bloop`, it looks for `bloop.json`, and for some reason if you have `C:\` at the start, it gets confused and doesn't understand it's a Windows path. Doing `\Users\...\bloop`, just dropping the `C:\` seems to work (though it then relies on scoop being installed on the system drive):

```powershell
coursier install --install-dir \Users\ginnu\scoop\apps\bloop\1.4.1 --default-channels=false --channel \Users\ginnu\scoop\apps\bloop\1.4.1 bloop-coursier
Wrote bloop-coursier
Warning: \Users\ginnu\scoop\apps\bloop\1.4.1 is not in your PATH
```

**Comment by Arthurm1** [comment]
Thanks @heksesang - I think you're right

I've raised an issue coursier/coursier#1741

**Comment by zzvara** [comment]
> Temporary workaround...
> 
> Uninstall Bloop if you have installed it...
> `scoop uninstall bloop`
> 
> Add the Bloop bucket
> `scoop bucket add bloop-stable https://github.com/scalacenter/scoop-bloop.git`
> 
> Edit the bucket file: `%home%/scoop/buckets/bloop-stable/bloop.json` (or wherever you installed Scoop) to be...
> 
> ```
> {
>   "version": "1.4.1",
>   "url": "https://github.com/scalacenter/bloop/releases/download/v1.4.1/bloop-coursier.json",
>   "hash": "sha256:2e6a873183e5e22712913bfdab1331d0a7792167c369fee5be0c83e27572fe12",
>   "depends": "coursier",
>   "bin": "bloop.bat",
>   "env_add_path": "$dir",
>   "env_set": {
>     "BLOOP_HOME": "$dir",
>     "BLOOP_IN_SCOOP": "true"
>   },
>   "installer": {
>     "script": "coursier install --install-dir $dir bloop"
>   }
> }
> ```
> 
> install bloop:
> `scoop install bloop`

I had the same problem, this fixed it for me with 1.4.3.

**Comment by fineconstant** [comment]
And same now with 1.4.8

**Comment by jozanek** [comment]
This was fixed a while ago. Both problems reported here:

1. `"bin": "bloop"` should be `"bin": "bloop.bat"`, and
2. coursier mangling the Windows `--channel` path that started with a drive letter (`C:\...`)

were addressed in commit `e118689d2` ("Fix scoop install script", #1729). The Scoop manifest now uses `"bin": "bloop.bat"` and drops `--channel` in favour of coursier's default channels:

```json
"bin": "bloop.bat",
"installer": { "script": "coursier install --install-dir $dir bloop" }
```

The fix first shipped in **v1.5.1** — the last report in this thread (1.4.8) predates it. The current live `scoop-bloop` manifest (v2.1.0) carries the fix, so `scoop install bloop` works on Windows today.

**Comment by tgodzik** [comment]
Thanks for checking!
