### ISSUE TITLE
Resolving ch.epfl.scala:bloop-frontend_2.12:1.4.1 timeout

### ISSUE THREAD

**Issue by user753** [scalacenter/bloop#1290]
I am using Windows 10 and I am behind the proxy
I installed bloop with coursier
but when I try to use bloop compile
```
No server running at 127.0.0.1:8212, let's fire one...
Resolving ch.epfl.scala:bloop-frontend_2.12:1.4.1...
error: Unexpected error when resolving Bloop server via coursier!
error: Error downloading ch.epfl.scala:bloop-frontend_2.12:1.4.1
  download error: Caught java.net.ConnectException: Connection timed out: connect (Connection timed out: connect) while downloading https://repo1.maven.org/maven2/ch/epfl/scala/bloop-frontend_2.12/1.4.1/bloop-frontend_2.12-1.4.1.pom
  download error: Caught java.net.ConnectException: Connection timed out: connect (Connection timed out: connect) while downloading https://dl.bintray.com/scalacenter/releases/ch/epfl/scala/bloop-frontend_2.12/1.4.1/bloop-frontend_2.12-1.4.1.pom
coursier.error.ResolutionError$CantDownloadModule: Error downloading ch.epfl.scala:bloop-frontend_2.12:1.4.1
  download error: Caught java.net.ConnectException: Connection timed out: connect (Connection timed out: connect) while downloading https://repo1.maven.org/maven2/ch/epfl/scala/bloop-frontend_2.12/1.4.1/bloop-frontend_2.12-1.4.1.pom
  download error: Caught java.net.ConnectException: Connection timed out: connect (Connection timed out: connect) while downloading https://dl.bintray.com/scalacenter/releases/ch/epfl/scala/bloop-frontend_2.12/1.4.1/bloop-frontend_2.12-1.4.1.pom
        at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:325)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversablaeLike.scala:237)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at coursier.Resolve$.validate(Resolve.scala:323)
        at coursier.Resolve.validate0$1(Resolve.scala:112)
        at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:156)
        at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
error: Server could not be started at None:None! Giving up...
```
Where can I put the proxy settings?

**Comment by Duhemm** [comment]
Hi @user753, thanks for the report.

The first time you start Bloop for a given version, `bloop` will be resolving the server using Coursier. You can configure the proxy by passing `-Dhttps.proxyHost=https://foobar.com -Dhttps.proxyPort=3123` to you call to `bloop`:

```
$ bloop about -Dhttps.proxyHost=https://foobar.com -Dhttps.proxyPort=3123
```

It shouldn't be necessary to pass these flags when you're using a Bloop versions that is already cached on your machine. We'll be adding this to the docs.

Gitter (https://gitter.im/scalacenter/bloop) is a better place for support questions.
