### ISSUE TITLE
Gradle plugin (1.4.4) regression: NPE while executing task: bloopInstall

### ISSUE THREAD

**Issue by marksutt** [scalacenter/bloop#1375]
Thanks for providing a Gradle plugin for bloop!

We use it for generating bloop config, so that we enjoy super fast compilation in the IDE.
We apply the plugin like:
```      
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {  "classpath"(group = "ch.epfl.scala", name = "gradle-bloop_2.12", version = "1.4.3")}
}
plugins {
    // Apply the scala plugin to add support for Scala
    scala

    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    // To easily launch
    application
}

apply(plugin = "bloop")

application {
    mainClass.set("com.foo.bar.Main")
}
```
But when trying to update to version 1.4.4, we get the following NPE when executing `./gradlew bloopInstall`:
```
Caused by: java.lang.NullPointerException
        at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeVal(JsonWriter.scala:325)
        at bloop.config.ConfigCodecs$$anon$8$$anon$10.e0(ConfigCodecs.scala:133)
        at bloop.config.ConfigCodecs$$anon$8$$anon$10.encodeValue(ConfigCodecs.scala:133)
        at bloop.config.ConfigCodecs$$anon$8$$anon$10.encodeValue(ConfigCodecs.scala:133)
        at bloop.config.ConfigCodecs$$anon$8.encodeValue(ConfigCodecs.scala:136)
        at bloop.config.ConfigCodecs$$anon$8.encodeValue(ConfigCodecs.scala:128)
        at bloop.config.ConfigCodecs$$anon$11$$anon$12.e1(ConfigCodecs.scala:171)
        at bloop.config.ConfigCodecs$$anon$11$$anon$12.e0(ConfigCodecs.scala:171)
        at bloop.config.ConfigCodecs$$anon$11$$anon$12.encodeValue(ConfigCodecs.scala:171)
        at bloop.config.ConfigCodecs$$anon$11$$anon$12.encodeValue(ConfigCodecs.scala:171)
        at bloop.config.ConfigCodecs$$anon$11.encodeValue(ConfigCodecs.scala:181)
        at bloop.config.ConfigCodecs$$anon$11.encodeValue(ConfigCodecs.scala:168)
        at bloop.config.ConfigCodecs$$anon$13.e0(ConfigCodecs.scala:200)
        at bloop.config.ConfigCodecs$$anon$13.encodeValue(ConfigCodecs.scala:200)
        at bloop.config.ConfigCodecs$$anon$13.encodeValue(ConfigCodecs.scala:200)
        at bloop.config.ConfigCodecs$$anon$14.e0(ConfigCodecs.scala:203)
        at bloop.config.ConfigCodecs$$anon$14.encodeValue(ConfigCodecs.scala:203)
        at bloop.config.ConfigCodecs$$anon$14.encodeValue(ConfigCodecs.scala:203)
        at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.write(JsonWriter.scala:587)
        at com.github.plokhotnyuk.jsoniter_scala.core.package$.writeToArray(package.scala:208)
        at bloop.config.ConfigCodecs$.toStr(ConfigCodecs.scala:218)
        at bloop.config.package$.write(package.scala:9)
        at bloop.config.package$.write(package.scala:11)
        at bloop.integrations.gradle.tasks.BloopInstallTask.generateBloopConfiguration(BloopInstallTask.scala:90)
        at bloop.integrations.gradle.tasks.BloopInstallTask.runBloopPlugin(BloopInstallTask.scala:52)
        at bloop.integrations.gradle.tasks.BloopInstallTask.run(BloopInstallTask.scala:30)
```

Without appling the application gradle plugin, `./gradlew bloopInstall` seems to work as expected.
So it looks like an incompatibility with the application plugin?

**Comment by Arthurm1** [comment]
Thanks for the report.

BloopInstall uses the application plugin to find the mainClassName which I guess in this case must be null.  I'll look to change the plugin to handle this.

For now, a workaround would be to specify a blank name which in Kotlin I guess would be something like...
```
application {
  setMainClassName("")
}
```

**Comment by marksutt** [comment]
Hey @Arthurm1, thanks for your fast reaction.

Sorry, I missed that snipped to define the main class when I tried to minimize our build file for creating this issue.. 
But even with it, we get the NPE.

I updated my first comment for completeness:
```
application {
    mainClass.set("com.foo.bar.Main")
}
```
Les me know if we can try/help somehow.

**Comment by Arthurm1** [comment]
There are 2 different ways to specify the main class

Could you try the following as a workaround rather than setting via the `mainClass` property...
```
application {
  setMainClassName("com.foo.bar.Main")
}
```

I'll look to add support for the property as it seems `mainClassName` is being deprecated

**Comment by marksutt** [comment]
Thanks for the hint, didn't know that there are two ways to specify the main class.
And with your suggestion: `setMainClassName` it works. :clap:
