### ISSUE TITLE
Failed to start test for laucher.

### ISSUE THREAD

**Issue by VladPodilnyk** [scalacenter/bloop#1381]
Hi, guys, I was trying to play  with bloop and to look around when found this. So, I basically finished the installation and just tried to run test in `laucher` project and it failed with the error I've attached below. Also, I've spotted that some tests pass like`BloopLoggerTest`,  but `BloopLoaderTest` fails with the same error I've mentioned. So, it's probably the issue on my side,  but I have no  clue what is wrong, so I am asking for help or maybe you could have a suggestion what could be the root of evil in this case.

```
Testing started at 00:15 ...
bloop/config/Config$CompileOrder
java.lang.NoClassDefFoundError: bloop/config/Config$CompileOrder
	at bloop.testing.BloopHelpers.$anonfun$writeFile$1(BloopHelpers.scala:331)
	at scala.util.Try$.apply(Try.scala:213)
	at bloop.testing.BloopHelpers.writeFile(BloopHelpers.scala:331)
	at bloop.testing.BloopHelpers.writeFile$(BloopHelpers.scala:328)
	at bloop.testing.BaseSuite.writeFile(BaseSuite.scala:37)
	at bloop.launcher.LauncherBaseSuite.<init>(LauncherBaseSuite.scala:61)
	at bloop.launcher.LauncherSpec.<init>(LauncherSpec.scala:29)
	at bloop.launcher.LatestMasterLauncherSpec$.<init>(LauncherSpec.scala:26)
	at bloop.launcher.LatestMasterLauncherSpec$.<clinit>(LauncherSpec.scala)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.jetbrains.plugins.scala.testingSupport.uTest.UTestSuiteRunner.getTestObject(UTestSuiteRunner.java:147)
	at org.jetbrains.plugins.scala.testingSupport.uTest.UTestSuiteRunner.doRunTestSuite(UTestSuiteRunner.java:75)
	at org.jetbrains.plugins.scala.testingSupport.uTest.UTestSuiteRunner.runTestSuite(UTestSuiteRunner.java:57)
	at org.jetbrains.plugins.scala.testingSupport.uTest.UTestSuiteRunner.runTestSuites(UTestSuiteRunner.java:45)
	at org.jetbrains.plugins.scala.testingSupport.uTest.UTestRunner.main(UTestRunner.java:12)
Caused by: java.lang.ClassNotFoundException: bloop.config.Config$CompileOrder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
Exception in thread "main" java.lang.NoClassDefFoundError: bloop/config/Config$CompileOrder
	at bloop.testing.BloopHelpers.$anonfun$writeFile$1(BloopHelpers.scala:331)
	at scala.util.Try$.apply(Try.scala:213)
	at bloop.testing.BloopHelpers.writeFile(BloopHelpers.scala:331)
	at bloop.testing.BloopHelpers.writeFile$(BloopHelpers.scala:328)
	at bloop.testing.BaseSuite.writeFile(BaseSuite.scala:37)
	at bloop.launcher.LauncherBaseSuite.<init>(LauncherBaseSuite.scala:61)
	at bloop.launcher.LauncherSpec.<init>(LauncherSpec.scala:29)
	at bloop.launcher.LatestMasterLauncherSpec$.<init>(LauncherSpec.scala:26)
	at bloop.launcher.LatestMasterLauncherSpec$.<clinit>(LauncherSpec.scala)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.jetbrains.plugins.scala.testingSupport.uTest.UTestSuiteRunner.getTestObject(UTestSuiteRunner.java:147)
	at org.jetbrains.plugins.scala.testingSupport.uTest.UTestSuiteRunner.doRunTestSuite(UTestSuiteRunner.java:75)
	at org.jetbrains.plugins.scala.testingSupport.uTest.UTestSuiteRunner.runTestSuite(UTestSuiteRunner.java:57)
	at org.jetbrains.plugins.scala.testingSupport.uTest.UTestSuiteRunner.runTestSuites(UTestSuiteRunner.java:45)
	at org.jetbrains.plugins.scala.testingSupport.uTest.UTestRunner.main(UTestRunner.java:12)
Caused by: java.lang.ClassNotFoundException: bloop.config.Config$CompileOrder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more

Process finished with exit code 1

```

**Comment by tgodzik** [comment]
Thanks for reporting! Might this have something to do with the java version? Or maybe the launcher jar got corrupted?

**Comment by VladPodilnyk** [comment]
@tgodzik, hi, thanks for coming here and for support! 
here is my `jenv versionsn` result 
```
❯ jenv versions
  system
* 1.8 (set by /Users/vpodilnyk/sandbox/bloop/.java-version)
  1.8.0.212
  11.0
  11.0.2
  12.0
  12.0.1
  openjdk64-1.8.0.212
  openjdk64-11.0.2
  openjdk64-12.0.1
``` 
here is what I have when run this command `java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home'
    java.home = /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre`
```
ava -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home'
    java.home = /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre
```

Oh, that's interesting, I found out that `<project-dir>/.bloop/bloop.json` does not contain any info about `javaHome`. Could be this, right?

**Comment by tgodzik** [comment]
It should pick up the right java version from Intellij anyway. I haven't noticed before, are you trying to run Bloop tests from Intellij? I have never tried that, but does it work in sbt itself?

Intellij seems to be missing the config module, so maybe export is not working properly. Could you try adding a dependency on the config module?

**Comment by VladPodilnyk** [comment]
@tgodzik, I am able to start test via `sbt test`. Originally, I've run them from Intelij. The project structure seems OK, I have  dependency on `config`. Anyway, I have the result I need, but it would be great to run test from IDE too. Since it is not critical for me, I dunno if we wanna pursue the issue, specially considering the fact that it's on my side. __Thanks a lot for you help__!
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/12114216/95254397-83548300-0828-11eb-838c-da75b23eb797.png">

**Comment by tgodzik** [comment]
@VladPodilnyk The reason might that Intellij doesn't work well with multiple Scala versions in the same module. The only other thing you could try is switching that module dependency with jsonConfig212 or jsonConfig213. If the tests have a different Scala version than the tests are actually running on then that could be the reason.

If that doesn't help, I would recommend running from sbt then or maybe trying out testing via BSP. Debugging sbt export might take a bit of time and it's hard to say if the fault is in the build definition or Intellij itself.

**Comment by VladPodilnyk** [comment]
@tgodzik, hi! Sorry, for such late response. I've had a bad luck trying to run tests via Intelij, but since `sbt test` works, I'll close the issue. Thank you a lot for help and support!!!
