### ISSUE TITLE
Unable to install via brew on macOS Catalina

### ISSUE THREAD

**Issue by hmemcpy** [scalacenter/bloop#1412]
Running:

> $ brew install scalacenter/bloop/bloop

getting:

```
==> Installing bloop from scalacenter/bloop
==> Downloading https://github.com/scalacenter/bloop/releases/download/v1.4.5/bash-completions
Already downloaded: /Users/hmemcpy/Library/Caches/Homebrew/downloads/e8643c1ac881908a70366b8da849dfb45cd544e941512975c9290b4686bd40fe--bash-completions
==> Downloading https://github.com/scalacenter/bloop/releases/download/v1.4.5/zsh-completions
Already downloaded: /Users/hmemcpy/Library/Caches/Homebrew/downloads/1e2c7db767190e6ff0a395407deffc63018336602f5e6a303745e4e96c99dbad--zsh-completions
==> Downloading https://github.com/scalacenter/bloop/releases/download/v1.4.5/fish-completions
Already downloaded: /Users/hmemcpy/Library/Caches/Homebrew/downloads/c20d312869a73d7ac1e3519f696fe5dd933062df84e03354ded2ac01027254d8--fish-completions
==> Downloading https://github.com/scalacenter/bloop/releases/download/v1.4.5/bloop-coursier.json
Already downloaded: /Users/hmemcpy/Library/Caches/Homebrew/downloads/92fe584730e6ea3c70fb13d7dcc4916712d1c2b32e80de9e1b072a6512bd6b3c--bloop-coursier.json
==> coursier install --install-dir bin --default-channels=false --channel channel bloop -J-Divy.home=/home/runner/.ivy2
Last 15 lines from /Users/hmemcpy/Library/Logs/Homebrew/bloop/01.coursier:
	at coursier.cache.FileCache.$anonfun$download$33(FileCache.scala:507)
	at coursier.cache.FileCache$$Lambda$956/0000000000000000.apply(Unknown Source)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.concurrent.Future$$$Lambda$550/0000000000000000.apply(Unknown Source)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.Future$$Lambda$545/0000000000000000.apply(Unknown Source)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.Promise$$Lambda$548/0000000000000000.apply(Unknown Source)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
```

<details>
<summary>Contents of my 01.coursier</summary>

    coursier
    install
    --install-dir
    bin
    --default-channels=false
    --channel
    channel
    bloop
    -J-Divy.home=/home/runner/.ivy2

    Downloading https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.12/1.4.5/bloopgun_2.12-1.4.5.pom
    Downloaded https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.12/1.4.5/bloopgun_2.12-1.4.5.pom
    Exception in thread "main" java.io.FileNotFoundException: /Users/hmemcpy/Library/Caches/Coursier/v1/.structure.lock (Operation not permitted)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
        at coursier.paths.CachePath.withStructureLock(CachePath.java:140)
        at coursier.cache.CacheLocks$.withStructureLock(CacheLocks.scala:21)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:38)
        at coursier.cache.FileCache.$anonfun$download$33(FileCache.scala:507)
        at coursier.cache.FileCache$$Lambda$956/0000000000000000.apply(Unknown Source)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.concurrent.Future$$$Lambda$550/0000000000000000.apply(Unknown Source)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.Future$$Lambda$545/0000000000000000.apply(Unknown Source)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.Promise$$Lambda$548/0000000000000000.apply(Unknown Source)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:836)

    HOMEBREW_VERSION: 2.5.11
    ORIGIN: https://github.com/Homebrew/brew
    HEAD: 07b3aa69f8dc5098437cf2562864558bae2d45aa
    Last commit: 9 days ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: 5cd013e5a9f88a7c35a3e97add9183807c9f2fbd
    Core tap last commit: 14 minutes ago
    Core tap branch: master
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_CASK_OPTS: []
    HOMEBREW_MAKE_JOBS: 12
    Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
    CPU: dodeca-core 64-bit kabylake
    Clang: 12.0 build 1200
    Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
    Curl: 7.64.1 => /usr/bin/curl
    Java: 11.0.8, 1.8.0_265
    macOS: 10.15.7-x86_64
    CLT: 12.0.26.2
    Xcode: N/A

    HOMEBREW_CC: clang
    HOMEBREW_CXX: clang++
    CFLAGS: -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11-openj9.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11-openj9.jdk/Contents/Home/include/darwin
    CXXFLAGS: -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11-openj9.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11-openj9.jdk/Contents/Home/include/darwin
    MAKEFLAGS: -j12
    CMAKE_PREFIX_PATH: /usr/local
    CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
    CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
    PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15
    HOMEBREW_GIT: git
    HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
    ACLOCAL_PATH: /usr/local/share/aclocal
    PATH: /Library/Java/JavaVirtualMachines/adoptopenjdk-11-openj9.jdk/Contents/Home/bin:/usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/coursier/bin:/usr/bin:/bin:/usr/sbin:/sbin

</details>

Seems that it's unable to create the `.structure.lock` file in the Cache directory. If I try to manually create an empty `.structure.lock` file, I get the same error (FileNotFoundException, even though the file is there.)

Am I holding it wrong? Thanks!

**Comment by tgodzik** [comment]
Thanks for reporting! Did you try to delete that lock file? I thinking it might have some strickt permissions set. Maybe if ever coursier was run via sudo? Is that possible?

**Comment by tgodzik** [comment]
The brew formula was recently updated, let us know if you are still having problems. We can reopen the issue then.
