### ISSUE TITLE
`JsonReaderException` when running `bloop projects`

### ISSUE THREAD

**Issue by clayton-sayer-hs** [scalacenter/bloop#1420]
I'm setting up a new laptop and have been having issues using Bloop, both on the command line and through IntelliJ. Both running `bloop projects` or loading the project via IntelliJ on any Scala project I've tried results in the same error:

```
❯ bloop projects
bloop.data.Project$ProjectReadException: Failed to load project from /Users/clayton.sayer/code/inbox/service-inbox-ingestion/.bloop/root.json
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:214)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[E] Failed to load project from /Users/clayton.sayer/code/inbox/service-inbox-ingestion/.bloop/contract-test-inbox-service-test.json
Caused by: com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderException: expected '{', offset: 0x00001f45, buf:
+----------+-------------------------------------------------+------------------+
|          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f | 0123456789abcdef |
+----------+-------------------------------------------------+------------------+
| 00001f20 | 20 20 20 20 5d 2c 0a 20 20 20 20 20 20 20 20 20 |     ],.          |
| 00001f30 | 20 20 20 22 72 75 6e 74 69 6d 65 43 6f 6e 66 69 |    "runtimeConfi |
| 00001f40 | 67 22 20 3a 20 5b 0a 20 20 20 20 20 20 20 20 20 | g" : [.          |
| 00001f50 | 20 20 20 5d 2c 0a 20 20 20 20 20 20 20 20 20 20 |    ],.           |
| 00001f60 | 20 20 22 63 6c 61 73 73 70 61 74 68 22 20 3a 20 |   "classpath" :  |
+----------+-------------------------------------------------+------------------+
```

In each of these projects it fails on `project.platform.runtimeConfig`, which it looks like it's assuming will be a JSON object when it's actually an empty array.

Replacing these empty arrays with the following seems to fix bloop command line, but trying to re-import the project in IntelliJ overwrites the dotfiles, re-breaking the `runtimeConfig`:
```
"runtimeConfig" : {
    "options": []
},
```

My system info:
```
❯ java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)

❯ bloop about
bloop v1.4.5

Using Scala v2.12.8 and Zinc v1.3.0-M4+45-d4354be3
Running on Java JDK v1.8.0_275 (/Users/clayton.sayer/Library/Java/JavaVirtualMachines/adopt-openjdk-1.8.0_275/Contents/Home/jre)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center (Jorge Vicente Cantero, Martin Duhem)

❯ coursier --version
2.0.7

❯ scala --version
Scala code runner version 2.13.4 -- Copyright 2002-2020, LAMP/EPFL and Lightbend, Inc.

❯ sbt --version
[info] 	0.13.18
sbt script version: 1.4.4
```

IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on November 30, 2020
Scala plugin 2020.3.16
MacOS Catalina 10.15.7

**Comment by clayton-sayer-hs** [comment]
It looks like this might be an issue with the latest version of IntelliJ and the json files it generates. I upgraded my old laptop from 2020.2 to 2020.3 and after re-importing the projects they started failing on the old laptop. I also compared the json files between 2020.2 and 2020.3 (different projects) and they're quite different:

2020.2:
```JSON
"platform" : {
    "name" : "jvm",
    "config" : {
        "home" : "/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre",
        "options" : [
            "-Duser.dir=/Users/clayton.sayer/code/inbox/message-actions"
        ]
    },
    "mainClass" : [
    ]
},
```

2020.3
```JSON
"platform" : {
    "name" : "jvm",
    "config" : {
        "home" : "/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre",
        "options" : [
            "-Duser.dir=/Users/clayton.sayer/code/inbox/graphql-gateway"
        ]
    },
    "mainClass" : [
    ],
    "runtimeConfig" : [
    ],
    "classpath" : [
    ],
    "resources" : [
    ]
},
```

I'll open a bug ticket with JetBrains, as this is likely a problem on their side.

**Comment by clayton-sayer-hs** [comment]
Here is [a YouTrack bug report for IntelliJ](https://youtrack.jetbrains.com/issue/IDEA-256752) that also describes this issue. Please feel free to close this issue ticket if you think this is solely a bug in IntelliJ.

**Comment by tgodzik** [comment]
Thanks for reporting! I think it's an issue that we fixed just after 1.4.5 release. Could you try updating the Bloop plugin to the newely released 1.4.6?

**Comment by clayton-sayer-hs** [comment]
Thanks for the quick response!

I tried updating bloop to 1.4.6 and restarting the server, but that doesn't seem to have helped, both in IntelliJ and with the bloop console:

```
❯ bloop help
No server running at 127.0.0.1:8212, let's fire one...
Resolving ch.epfl.scala:bloop-frontend_2.12:1.4.6...
Starting bloop server at 127.0.0.1:8212...
Attempting a connection to the server...
Attempting a connection to the server...
Attempting a connection to the server...
Attempting a connection to the server...
bloop 1.4.6
Usage: bloop [options] [command] [command-options]


Available commands: about, autocomplete, bsp, clean, compile, configure, console, help, link, projects, run, test
Type `bloop 'command' --help` for help on an individual command

Type `--nailgun-help` for help on the Nailgun CLI tool.
❯ bloop projects
bloop.data.Project$ProjectReadException: Failed to load project from /Users/clayton.sayer/code/inbox/graphql-gateway/.bloop/contract-test-tops.json
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:214)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderException: expected '{', offset: 0x0000916a, buf:
+----------+-------------------------------------------------+------------------+
|          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f | 0123456789abcdef |
+----------+-------------------------------------------------+------------------+
| 00009140 | 20 20 20 20 20 20 20 20 20 5d 2c 0a 20 20 20 20 |          ],.     |
| 00009150 | 20 20 20 20 20 20 20 20 22 72 75 6e 74 69 6d 65 |         "runtime |
| 00009160 | 43 6f 6e 66 69 67 22 20 3a 20 5b 0a 20 20 20 20 | Config" : [.     |
| 00009170 | 20 20 20 20 20 20 20 20 5d 2c 0a 20 20 20 20 20 |         ],.      |
| 00009180 | 20 20 20 20 20 20 20 22 63 6c 61 73 73 70 61 74 |        "classpat |
+----------+-------------------------------------------------+------------------+
bloop.data.Project$ProjectReadException: Failed to load project from /Users/clayton.sayer/code/inbox/graphql-gateway/.bloop/contract-test-inbox-service.json
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:214)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderException: expected '{', offset: 0x000092bf, buf:
+----------+-------------------------------------------------+------------------+
|          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f | 0123456789abcdef |
+----------+-------------------------------------------------+------------------+
| 00009290 | 5b 0a 20 20 20 20 20 20 20 20 20 20 20 20 5d 2c | [.            ], |
| 000092a0 | 0a 20 20 20 20 20 20 20 20 20 20 20 20 22 72 75 | .            "ru |
| 000092b0 | 6e 74 69 6d 65 43 6f 6e 66 69 67 22 20 3a 20 5b | ntimeConfig" : [ |
| 000092c0 | 0a 20 20 20 20 20 20 20 20 20 20 20 20 5d 2c 0a | .            ],. |
| 000092d0 | 20 20 20 20 20 20 20 20 20 20 20 20 22 63 6c 61 |             "cla |
+----------+-------------------------------------------------+------------------+
bloop.data.Project$ProjectReadException: Failed to load project from /Users/clayton.sayer/code/inbox/graphql-gateway/.bloop/contract-test-inbox-service-it.json
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:214)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderException: expected '{', offset: 0x0000914c, buf:
+----------+-------------------------------------------------+------------------+
|          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f | 0123456789abcdef |
+----------+-------------------------------------------------+------------------+
| 00009120 | 20 20 20 20 20 20 20 20 20 20 20 5d 2c 0a 20 20 |            ],.   |
| 00009130 | 20 20 20 20 20 20 20 20 20 20 22 72 75 6e 74 69 |           "runti |
| 00009140 | 6d 65 43 6f 6e 66 69 67 22 20 3a 20 5b 0a 20 20 | meConfig" : [.   |
| 00009150 | 20 20 20 20 20 20 20 20 20 20 5d 2c 0a 20 20 20 |           ],.    |
| 00009160 | 20 20 20 20 20 20 20 20 20 22 63 6c 61 73 73 70 |          "classp |
+----------+-------------------------------------------------+------------------+
bloop.data.Project$ProjectReadException: Failed to load project from /Users/clayton.sayer/code/inbox/graphql-gateway/.bloop/integration-tests-it.json
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:214)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderException: expected '{', offset: 0x00008bc8, buf:
+----------+-------------------------------------------------+------------------+
|          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f | 0123456789abcdef |
+----------+-------------------------------------------------+------------------+
| 00008ba0 | 20 20 20 20 20 20 20 5d 2c 0a 20 20 20 20 20 20 |        ],.       |
| 00008bb0 | 20 20 20 20 20 20 22 72 75 6e 74 69 6d 65 43 6f |       "runtimeCo |
| 00008bc0 | 6e 66 69 67 22 20 3a 20 5b 0a 20 20 20 20 20 20 | nfig" : [.       |
| 00008bd0 | 20 20 20 20 20 20 5d 2c 0a 20 20 20 20 20 20 20 |       ],.        |
| 00008be0 | 20 20 20 20 20 22 63 6c 61 73 73 70 61 74 68 22 |      "classpath" |
+----------+-------------------------------------------------+------------------+
bloop.data.Project$ProjectReadException: Failed to load project from /Users/clayton.sayer/code/inbox/graphql-gateway/.bloop/contract-test-srs-it.json
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:214)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderException: expected '{', offset: 0x00008bc8, buf:
+----------+-------------------------------------------------+------------------+
|          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f | 0123456789abcdef |
+----------+-------------------------------------------------+------------------+
| 00008ba0 | 20 20 20 20 20 20 20 5d 2c 0a 20 20 20 20 20 20 |        ],.       |
| 00008bb0 | 20 20 20 20 20 20 22 72 75 6e 74 69 6d 65 43 6f |       "runtimeCo |
| 00008bc0 | 6e 66 69 67 22 20 3a 20 5b 0a 20 20 20 20 20 20 | nfig" : [.       |
| 00008bd0 | 20 20 20 20 20 20 5d 2c 0a 20 20 20 20 20 20 20 |       ],.        |
| 00008be0 | 20 20 20 20 20 22 63 6c 61 73 73 70 61 74 68 22 |      "classpath" |
+----------+-------------------------------------------------+------------------+
bloop.data.Project$ProjectReadException: Failed to load project from /Users/clayton.sayer/code/inbox/graphql-gateway/.bloop/contract-test-mas.json
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:214)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderException: expected '{', offset: 0x0000915a, buf:
+----------+-------------------------------------------------+------------------+
|          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f | 0123456789abcdef |
+----------+-------------------------------------------------+------------------+
| 00009130 | 20 20 20 20 20 20 20 20 20 5d 2c 0a 20 20 20 20 |          ],.     |
| 00009140 | 20 20 20 20 20 20 20 20 22 72 75 6e 74 69 6d 65 |         "runtime |
| 00009150 | 43 6f 6e 66 69 67 22 20 3a 20 5b 0a 20 20 20 20 | Config" : [.     |
| 00009160 | 20 20 20 20 20 20 20 20 5d 2c 0a 20 20 20 20 20 |         ],.      |
| 00009170 | 20 20 20 20 20 20 20 22 63 6c 61 73 73 70 61 74 |        "classpat |
+----------+-------------------------------------------------+------------------+
bloop.data.Project$ProjectReadException: Failed to load project from /Users/clayton.sayer/code/inbox/graphql-gateway/.bloop/contract-test-inbox-service-test.json
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:214)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
	at bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
[E] Failed to load project from /Users/clayton.sayer/code/inbox/graphql-gateway/.bloop/root.json
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)%
```

I've also tried cleaning all the generated files and re-importing it in IntelliJ to see if that would fix it, but it still fails, with those extra fields causing exceptions in Bloop.

Please let me know if there's anything else you'd like me to try out.

**Comment by tgodzik** [comment]
Ach sorry! You need to change the sbt plugin versions and reimport the build via `bloopInstall`. I wasn't too clear about that.

**Comment by clayton-sayer-hs** [comment]
Hmm... We don't actually have the bloop plugin installed as an SBT plugin in any of our repos. We all just have it as a regular SBT project and use IntelliJ's File -> New -> Project from Existing Sources and import the project as BSP there. It may be that JetBrains needs to update the bloop plugin in their Scala plugin for this to be fixed.

I'll try adding the plugin to our SBT plugins for a single project and see if that fixes it, but I don't think it's something I can do to all of our repos, and still might not fix it, as IntelliJ overwrites the project json files very often.

**Comment by tgodzik** [comment]
Ach! It might be that Intellij somehow does add this plugin automatically. Not sure how it works, but most likely they just need to bump a dependency. It might be nothing we can do from our side at this time.

Other option is to upgrade sbt, since this problem only with Scala 2.10, which sbt 0.13 uses.

**Comment by clayton-sayer-hs** [comment]
Good to know that the problem only affects sbt 0.13. For all our Play 2.6+ services I'll try to get them updated to sbt 1.x, but we have a few services that are unfortunately still on Scala 2.11/Play 2.5 which requires sbt 0.13. Updating them is in the works but won't be for a couple months.

In the mean time, there's the ticket open with JetBrains that I've linked to this ticket, and the [PR that fixes the issue](https://github.com/scalacenter/bloop/pull/1398), so they can update the plugin on their side.

Thanks so much for the help Tomasz!

**Comment by tgodzik** [comment]
@clayton-sayer-hs I just realised you could also workaround it by:
- adding an additional `bloop.sbt` file to project, that just adds the bloop plugin:
`addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.6")`
- add that file to gitignore
- use `sbt bloopInstall` to generate the configuration file that should be picked correctly by Bloop
- if you don't reimport via Intellij everything should work ok
