### ISSUE TITLE
Test infrastructure is (spuriously) causing a null pointer exception

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#146]
Merging #136 made the CI failed with this error message:

```[error] Error: Total 39, Failed 0, Errors 0, Passed 39
[error] Error during tests:
[error] 	Forked test harness failed: java.lang.NullPointerException
[error] 	at sbt.TestEvent$.$anonfun$overallResult$1(TestReportListener.scala:108)
[error] 	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:56)
[error] 	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:64)
[error] 	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
[error] 	at scala.collection.TraversableOnce./:(TraversableOnce.scala:151)
[error] 	at scala.collection.TraversableOnce./:$(TraversableOnce.scala:151)
[error] 	at scala.collection.AbstractTraversable./:(Traversable.scala:104)
[error] 	at sbt.TestEvent$.overallResult(TestReportListener.scala:107)
[error] 	at sbt.TestEvent$$anon$1.<init>(TestReportListener.scala:102)
[error] 	at sbt.TestEvent$.apply(TestReportListener.scala:101)
[error] 	at sbt.React.react(ForkTests.scala:171)
[error] 	at sbt.ForkTests$Acceptor$2$.run(ForkTests.scala:96)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (frontend/test:test) sbt.TestsFailedException: Tests unsuccessful
```
  
I restarted the process, we'll see if it's an spurious error or not.

**Comment by jvican** [comment]
Seems it was a spurious error. Let's hope it doesn't show up anymore, otherwise that'd be a sign this is, most likely, a concurrency issue.

**Comment by Duhemm** [comment]
I'm wondering if it's not due to the forked JVM having too little memory to run the tests. I was seeing this problem in #124, and I think I didn't see it after I pushed this commit: https://github.com/scalacenter/bloop/pull/124/commits/c803ad39c5f5881a949219aec8f87de07eb3eac4

**Comment by jvican** [comment]
Maybe, closing preemptively.
