### ISSUE TITLE
No longer able to run with Coursier launch - regression from 1.4.6 to 1.4.7

### ISSUE THREAD

**Issue by przemek-pokrywka** [scalacenter/bloop#1463]
Hi,
```shell
cs launch ch.epfl.scala:bloopgun_2.12:1.4.6 -- about
```
runs fine, but
```shell
cs launch ch.epfl.scala:bloopgun_2.12:1.4.7 -- about
```
fails with error:
```
No server running at 127.0.0.1:8212, let's fire one...
Resolving ch.epfl.scala:bloop-frontend_2.12:1.4.7...
Exception in thread "main" bloop.shaded.coursier.util.Task$WrappedException: java.lang.NoClassDefFoundError: scala/collection/compat/immutable/LazyList$
	at bloop.shaded.coursier.util.Task$.wrap(Task.scala:88)
	at bloop.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.NoClassDefFoundError: scala/collection/compat/immutable/LazyList$
	at bloop.shaded.coursier.core.ResolutionProcess$.uniqueModules$1(ResolutionProcess.scala:416)
	at bloop.shaded.coursier.core.ResolutionProcess$.fetchAll(ResolutionProcess.scala:423)
	at bloop.shaded.coursier.core.ResolutionProcess.run(ResolutionProcess.scala:28)
	at bloop.shaded.coursier.Resolve$.runProcess(Resolve.scala:303)
	at bloop.shaded.coursier.Resolve.run$1(Resolve.scala:110)
	at bloop.shaded.coursier.Resolve.ioWithConflicts0(Resolve.scala:160)
	at bloop.shaded.coursier.Resolve.$anonfun$ioWithConflicts$1(Resolve.scala:171)
	at bloop.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at bloop.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at bloop.shaded.coursier.util.Task$.wrap(Task.scala:84)
	... 9 more
Caused by: java.lang.ClassNotFoundException: scala.collection.compat.immutable.LazyList$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 19 more
```

and trying to add extra jars:
```shell
cs launch --extra-jars $(cs fetch org.scala-lang:scala-library:2.13.4) --jvm 8 ch.epfl.scala:bloopgun_2.12:1.4.7 -- about
```
doesn't help.

I suspect that something might be missing within the 1.4.7 jar, I'll appreciate any clues.

**important note**
This happens only when no Bloop server is running.

**Comment by tgodzik** [comment]
Thanks for reporting! This is probably an issue with the upgrade of coursier we did recently. What version of coursier are you using?

**Comment by przemek-pokrywka** [comment]
Coursier 2.0.12

**Comment by tgodzik** [comment]
I will take a look, not sure exactly what is happening since this LazyList should be available. This might something that I misunderstood about shadowing though.

Is it possible for you to run `cs install bloop` ?

**Comment by przemek-pokrywka** [comment]
Yes, `cs install bloop`, followed by `bloop about` works fine.

Running `cs launch bloop -- about` fails with the mentioned LazyList error.

**Comment by przemek-pokrywka** [comment]
@tgodzik regarding your shadowing comment, have you noticed that the missing class is from `compat` package (`scala.collection.compat.immutable`)?

That package is missing in Scala 2.12, it is present in Scala 2.13.

**Comment by tgodzik** [comment]
It think it's the scala-collection-compat library which adds the LazyList for 2.12 so that it's easier to crosscompile coursier. Not sure why it's a problem, but I added it to ignored shading workspace, which I might need to unignore.

**Comment by przemek-pokrywka** [comment]
The missing Lazy List class needs to be somehow supplied to the shadowed Coursier if `cs launch` is to work.

Thanks for the scala-collection-compat remark, I managed to make `cs launch` work using:

```shell
cs launch ch.epfl.scala::bloopgun:1.4.7 \
  --extra-jars $(cs fetch -p org.scala-lang.modules:scala-collection-compat_2.12:2.4.2) -- about
```

Can the problem with the current configuration of shadowing be that the `scala` namespace is excluded and the compat classes are from `scala...` package tree?

**Comment by tgodzik** [comment]
Yes, that's what I think. Excluding seemed safe as it's binary compatible for the most parts and Bloop itself is not using it. However, I wonder if excluding means that it's not added to jar instead of just not being shaded.

**Comment by przemek-pokrywka** [comment]
It's not added to the jar, I've checked. Meanwhile Coursier still expects it to be there.
