### ISSUE TITLE
sbt plugin sbt-compat no longer found

### ISSUE THREAD

**Issue by Sciss** [scalacenter/bloop#1543]
Hi there. I try to open the bloop root dir in IntelliJ. It tries to create model from sbt build, but ends up with

```
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.github.cb372:sbt-explicit-dependencies:0.2.16 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 		com.jsuereth:sbt-pgp:2.1.1 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 		com.typesafe.sbt:sbt-license-report:1.2.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 		com.dwijnand:sbt-compat:1.2.6 (scalaVersion=2.12, sbtVersion=1.0)
```

How to solve this? I want to navigate the sources inside IntelliJ.

**Comment by tgodzik** [comment]
It might be helpful to use BSP and Bloop support in Intellij, since that seems to work in Metals, so I suspect it should also be good in Intellij.

**Comment by Sciss** [comment]
Hmmm, I tried via New-Project-from-existing-sources and explicitly specifying External-model-BSP / sbt-with-bloop based project, but the same happens, these dependencies are tried and failed.

**Comment by tgodzik** [comment]
Are you behind a proxy maybe? I can't seem to reproduce the issue in sbt. Are you able to do at least `sbt compile` ?

**Comment by Sciss** [comment]
Not behind a proxy, tried different networks. `sbt compile` also fails. I'm at e7d4e01ed0ae1d7ddbaa41dac85cbd6b71005ca4

**Comment by Sciss** [comment]
Hold on. These are my global sbt plugins. Seems to be related to https://github.com/cb372/sbt-explicit-dependencies/issues/102 - still weird that this only comes from the bloop project and not any of the gazillions of other sbt based projects I'm using.

**Comment by Sciss** [comment]
Hmmm, not fully. sbt-compat is not a global plugin of mine, I think bloop uses it. Seems also affected by bintray having disappeared. Opening an issue [here](https://github.com/dwijnand/sbt-compat/issues/66)

**Comment by tgodzik** [comment]
I can't find reference to ` sbt-compat` anywhere in the codebase. Are you sure it is caused by Bloop? If that was the case all the CI build should be failing.

**Comment by Sciss** [comment]
Here is a bit more info, I think it is created by `sbtBloopBuildShadedJar`. The whole thing looks very contrieved anyway as there at least _four_ levels of projects: `project/project/project/project`. Oof.

Here is the relevant output after running again from total clean state:

```
[info] loading project definition from ~/Documents/devel/bloop/project/project
[info] Wrote ~/Documents/devel/bloop/project/project/sbt-bloop-build-shaded-naked/target/scala-2.12/sbt-bloop-build-shaded-naked_2.12-1.0.0-SNAPSHOT.pom
[info] Updating 
https://repo1.maven.org/maven2/org/eclipse/xtend/org.eclipse.xtend.lib/maven-metadata.xml
  No new update since 2021-05-27 14:33:51
[info] Resolved  dependencies
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.dwijnand:sbt-compat:1.2.6 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[info] compiling 47 Scala sources and 11 Java sources to ~/Documents/devel/bloop/project/project/target/sbt-bloop-build-shaded/target/scala-2.12/sbt-1.0/classes ...
[error] ~/Documents/devel/bloop/integrations/sbt-bloop/src/main/scala-sbt-1.0/bloop/integrations/sbt/Offloader.scala:477:35: overloaded method value apply with alternatives:
[error]   (groups: Array[xsbti.compile.OutputGroup])xsbti.compile.Output <and>
[error]   (groups: (java.nio.file.Path, java.nio.file.Path)*)xsbti.compile.Output <and>
[error]   (dir: java.nio.file.Path)xsbti.compile.Output
[error]  cannot be applied to (java.io.File)
[error]     val output = sbt.internal.inc.CompileOutput(project.classesDir.toFile)
[error]                                   ^
[error] ~/Documents/devel/bloop/integrations/sbt-bloop/src/main/scala-sbt-1.0/bloop/integrations/sbt/Offloader.scala:478:80: type mismatch;
[error]  found   : java.io.File
[error]  required: java.nio.file.Path
[error]     val classpath = project.classpath.map(p => xsbti.compile.FileHash.create(p.toFile, 0)).toArray
[error]                                                                                ^
[error] ~/Documents/devel/bloop/integrations/sbt-bloop/src/main/scala-sbt-1.0/bloop/integrations/sbt/Offloader.scala:481:52: type mismatch;
[error]  found   : Array[Nothing]
[error]  required: Array[xsbti.compile.FileHash]
[error] Note: Nothing <: xsbti.compile.FileHash, but class Array is invariant in type T.
[error] You may wish to investigate a wildcard type such as `_ <: xsbti.compile.FileHash`. (SLS 3.2.10)
[error]     val options = xsbti.compile.MiniOptions.create(classpath, scalacOptions, javacOptions)
[error]                                                    ^
[error] three errors found
[error] sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-compat;sbtVersion=1.0;scalaVersion=2.12:1.2.6
[error]   Not found
[error]   Not found
[error]   not found: ~/.ivy2/local/com.dwijnand/sbt-compat/scala_2.12/sbt_1.0/1.2.6/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-compat_2.12_1.0/1.2.6/sbt-compat-1.2.6.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3678)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (sbtBloopBuildShadedNakedJar / update) sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-compat;sbtVersion=1.0;scalaVersion=2.12:1.2.6
[error]   Not found
[error]   Not found
[error]   not found: ~/.ivy2/local/com.dwijnand/sbt-compat/scala_2.12/sbt_1.0/1.2.6/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-compat_2.12_1.0/1.2.6/sbt-compat-1.2.6.pom
[error] (sbtBloopBuildShadedJar / Compile / compileIncremental) Compilation failed
```

You see, there are sbt project compilation errors because of File / Path mismatch, which I _guess_ is where sbt-compat was supposed to kick in.

**Comment by tgodzik** [comment]
Are you sure that you don't have an old Bloop branch or that it's not declared somewhere in you env? On the newest Bloop master:
- no `sbt-compat` can be found in the project
- I don't have it on my machine and everything publishes ok
- I asked a collegue to compile Bloop, who has never did that before and it worked for him

I just don't see any possibility that it's being caused by Bloop itself. Maybe it has soemthing to do with our local sbt version?

**Comment by Sciss** [comment]
After recloning the repo and wiping `~/.sbt/1.0`, it seems something is reset. I now get this which I had never seen before:
```
[error] 
[error] It looks like you didn't fully set up Bloop after cloning (git submodules are missing).
[error] Read the contributing guide for more information: https://scalacenter.github.io/bloop/docs/contributing-guide#set-the-repository-up
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```
So closing for now, as have move on to other things; I guess it was a local problem somehow.

**Comment by tgodzik** [comment]
> After recloning the repo and wiping `~/.sbt/1.0`, it seems something is reset. I now get this which I had never seen before:
> 
> ```
> [error] 
> [error] It looks like you didn't fully set up Bloop after cloning (git submodules are missing).
> [error] Read the contributing guide for more information: https://scalacenter.github.io/bloop/docs/contributing-guide#set-the-repository-up
> Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
> ```
> 
> So closing for now, as have move on to other things; I guess it was a local problem somehow.

That's expected. You need to do `git submodule update --init` and also install `clang`
