### ISSUE TITLE
Release 1.4.9 broken in Gradle 7.2

### ISSUE THREAD

**Issue by aishfenton** [scalacenter/bloop#1569]
Since upgrading to Bloop `1.4.9`, and Gradle `7.2`, I'm seeing below error. Downgrading to Bloop 1.4.8 fixes it. Unfortunately it's an internal project, so I can't post the full gradle file here.
 

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myPronject:configureBloopInstall'.
...
Caused by: java.lang.NoSuchMethodError: org.gradle.api.tasks.TaskInputs.property(Ljava/lang/String;Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskInputs;
        at bloop.integrations.gradle.tasks.ConfigureBloopInstallTask.run(ConfigureBloopInstallTask.scala:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
```

**Comment by aishfenton** [comment]
Scratch that. Clearly out the gradle dependency cache resolved it.
