### ISSUE TITLE
Incorrect stdout/stderr lines positions

### ISSUE THREAD

**Issue by dos65** [scalacenter/bloop#1630]
Having the following source:
```scala
object Main {
  
  def main(arg: Array[String]): Unit = {
    val lst = (1 to 20).toList
    println(lst.mkString("\n"))
    ???
  }
}
```

The output from `bloop run` or from run in Metals prints sterr lines earlier than it should be.
Output from bloop:
```
1
2
3
[E] Exception in thread "main" scala.NotImplementedError: an implementation is missing
4
5
6
7
8
9
10
[E] 	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:288)
[E] 	at example.Main$.main(Main.scala:8)
[E] 	at example.Main.main(Main.scala)
```

Output from `sbt run` - expected one:
```
sbt:scala2> run
[info] compiling 1 Scala source to /home/dos65/projects/metals/samples/scala2/target/scala-2.12/classes ...
[info] running example.Main 
1
2
3
4
5
6
7
8
9
10
[error] (run-main-1) scala.NotImplementedError: an implementation is missing
[error] scala.NotImplementedError: an implementation is missing
[error] 	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:288)
[error] 	at example.Main$.main(Main.scala:8)
[error] 	at example.Main.main(Main.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 0 s, completed Dec 20, 2021, 8:58:18 PM
sbt:scala2> 
```

**Comment by jozanek** [comment]
Still reproducible on bloop v2.1.0 (a program alternating `System.out.println` / `System.err.println`
scrambles immediately), but I think this is inherent to forking rather than a bug bloop can fix for free.

`Forker` gives the child two separate pipes and drains them with two threads
([Forker.scala#L200](https://github.com/scalacenter/bloop/blob/85fb6a7aea4bd0713a9d61160a133d8d5e1623c8/frontend/src/main/scala/bloop/exec/Forker.scala#L200),
[#L206-L207](https://github.com/scalacenter/bloop/blob/85fb6a7aea4bd0713a9d61160a133d8d5e1623c8/frontend/src/main/scala/bloop/exec/Forker.scala#L206-L207)).
Once the writes land in two pipes the relative order isn't recorded anywhere, so no reader can recover it.
To rule out bloop's own machinery I drained the same child from a bare harness into an in-memory list —
no sockets, no logging — and counted deviations from strict `OUT i` / `ERR i` alternation:

| setup | out-of-order lines (of 60), 3 runs |
|---|---|
| two pipes, two reader threads | 56, 56, 56 |
| `redirectErrorStream(true)` | 0, 0, 0 |

So batching, smaller buffers or faster draining won't help. A terminal only gets this right because both
fds point at the same tty and the kernel serializes the writes.

On the sbt comparison: `sbt run` is in-process by default, hence one sink and correct order by
construction. With `fork := true` sbt scrambles identically (`[info] OUT 1`, `[error] ERR 1`,
`[info] OUT 2 … OUT 26`, `[error] ERR 2`, …). The difference is fork vs. no-fork, not bloop vs. sbt.

The one real fix is `redirectErrorStream(true)`, but `Forker.run` is shared by run/test/source
generators/DAP and the stderr channel is load-bearing: `DebuggeeLogger` maps `error` to DAP
`category: "stderr"`, BSP to `MessageType.Error`, and `RunSpec` asserts a failed JVM launch arrives as an
error. Alternatives that keep the distinction (PTY, or a wrapper `main` that tags both streams onto one fd)
are a lot of machinery — and the wrapper adds stack frames to user tracebacks, visible in this issue's own
repro output.

Suggest closing as a known limitation of running in a forked process, unless the interleaving is actually
hurting a workflow in Metals — happy to implement a fix if maintainers would rather trade the stdout/stderr
distinction for exact ordering.

**Comment by tgodzik** [comment]
MAkes sense that it's a limitation. Thanks for investigating!
