### ISSUE TITLE
Java compiler with semanticdb options fails on Jdk17

### ISSUE THREAD

**Issue by dos65** [scalacenter/bloop#1651]
To reproduce, I've opened the [scala-cli repository](https://github.com/VirtusLab/scala-cli) using the latest Metals snapshot
And got the following error in log:
```
2022.01.11 14:16:18 WARN  Javac is running in 'local' mode. These flags have been removed:
2022.01.11 14:16:18 WARN  Javac is running in 'local' mode. These flags have been removed:
2022.01.11 14:16:18 WARN  	-J--add-exports, -Jjdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
2022.01.11 14:16:18 WARN  	-J--add-exports, -Jjdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
2022.01.11 14:16:18 ERROR An exception has occurred in the compiler (17.0.1). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
2022.01.11 14:16:18 ERROR java.lang.IllegalAccessError: class com.sourcegraph.semanticdb_javac.SemanticdbPlugin (in unnamed module @0x130fee71) cannot access class com.sun.tools.javac.api.BasicJavacTask (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x130fee71
2022.01.11 14:16:18 ERROR 	at com.sourcegraph.semanticdb_javac.SemanticdbPlugin.init(SemanticdbPlugin.java:19)
2022.01.11 14:16:18 ERROR 	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugin(BasicJavacTask.java:255)
2022.01.11 14:16:18 ERROR An exception has occurred in the compiler (17.0.1). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
2022.01.11 14:16:18 ERROR 	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:229)
2022.01.11 14:16:18 ERROR java.lang.IllegalAccessError: class com.sourcegraph.semanticdb_javac.SemanticdbPlugin (in unnamed module @0x130fee71) cannot access class com.sun.tools.javac.api.BasicJavacTask (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x130fee71
2022.01.11 14:16:18 ERROR 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:204)
2022.01.11 14:16:18 ERROR 	at com.sourcegraph.semanticdb_javac.SemanticdbPlugin.init(SemanticdbPlugin.java:19)
2022.01.11 14:16:18 ERROR 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:101)
2022.01.11 14:16:18 ERROR 	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugin(BasicJavacTask.java:255)
2022.01.11 14:16:18 ERROR 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
2022.01.11 14:16:18 ERROR 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
2022.01.11 14:16:18 ERROR 	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:229)
2022.01.11 14:16:18 ERROR 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
2022.01.11 14:16:18 ERROR 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:204)
2022.01.11 14:16:18 ERROR 	at bloop.CompilerCache$BloopJavaCompiler.run(CompilerCache.scala:271)
```

It seems that in case if there are `-J` flags we need to force bloop to use ForkedJavaCompiler instead of local one.

**Comment by tgodzik** [comment]
> It seems that in case if there are -J flags we need to force bloop to use ForkedJavaCompiler instead of local one.

Yeah, that's what I was meaning to take a look into.

**Comment by dos65** [comment]
@tgodzik Ok, will look at it
