### ISSUE TITLE
Scala 2.13 variant of the bloop plugin for Gradle is not available

### ISSUE THREAD

**Issue by q10** [scalacenter/bloop#1716]
We have several projects that use gradle for our builds, and one of the gradle plugins that we depend on has recently updated its dependency on `org.scala-lang:scala-library` from `2.12.x` to `2.13.x`.  This ends up breaking the gradle bloop plugin (currently dependent on Scala 2.12.x), where any task launched with `./gradlew` immediately fail with the following compatibility error (abridged):

```
Caused by: java.lang.NoSuchMethodError: 'scala.collection.GenTraversable scala.collection.Seq$.empty()'
        at bloop.integrations.gradle.BloopPlugin.apply(BloopPlugin.scala:19)
        at bloop.integrations.gradle.BloopPlugin.apply(BloopPlugin.scala:17)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:187)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:52)
```

I did not find a 2.13 variant of the bloop plugin for Gradle, though I see 2.13 variants available for maven and sbt.  Can we get a 2.13 variant of the bloop plugin for Gradle published?

**Comment by kpodsiad** [comment]
Hi @q10!
Indeed, there is no 2.13 Gradle plugin. I'll take a look at this.

**Comment by kpodsiad** [comment]
@q10 Could you try `1.4.13-70-d6f16202`? I cross-compiled plugin in https://github.com/scalacenter/bloop/pull/1717.

**Comment by kpodsiad** [comment]
Glad to hear that it works @q10!

**Comment by kpodsiad** [comment]
By the way, do you use bloop with Metals or Intellij?
