### ISSUE TITLE
RuntimeException: Could not find any viable Base64 encoder

### ISSUE THREAD

**Issue by michelou** [scalacenter/bloop#1718]
Here are 2 scenarios (Windows 11 Pro) illustrating the same issue : 

### Scenario 1 : Java 8

```
> where python java
c:\opt\Python-3.10.4\python.exe
C:\opt\jdk-temurin-1.8.0u322-b06\bin\java.exe

>echo %JAVA_HOME%& echo %PYTHON_HOME%
C:\opt\jdk-temurin-1.8.0u322-b06
C:\opt\Python-3.10.4
```

**Test 1a** with standalone executable [`bloop-x86_64-pc-win32.exe`](https://github.com/scalacenter/bloop/releases/tag/v1.4.13) : 

```
> c:\opt\bloop-1.4.13\bloop.exe server
Attempting a connection to the server...
Resolving ch.epfl.scala:bloop-frontend_2.12:1.4.13...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315)
        at coursierapi.shaded.coursier.cache.shaded.dirs.ProjectDirectories.from(ProjectDirectories.java:298)
        [...]
        at coursierapi.Fetch.create(Fetch.java:99)
        at bloop.bloopgun.core.DependencyResolution$.resolveWithErrors(DependencyResolution.scala:62)
        [...]
        at bloop.bloopgun.Bloopgun.main(Bloopgun.scala)
Caused by: java.lang.RuntimeException: Could not find any viable Base64 encoder! (java.util.Base64 failed with: java.util.Base64$Encoder.encodeToString([B))
        at coursierapi.shaded.coursier.cache.shaded.dirs.Util.initBase64Encoding(Util.java:188)
        at coursierapi.shaded.coursier.cache.shaded.dirs.Util.toUTF16LEBase64(Util.java:170)
        at coursierapi.shaded.coursier.cache.shaded.dirs.Util.<clinit>(Util.java:49)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        ... 20 more
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder. This exception was synthesized during native image building from a call to java.lang.Class.forName(String) with constant arguments.
        at coursierapi.shaded.coursier.cache.shaded.dirs.Util.initBase64Encoding(Util.java:185)
        ... 24 more
```

**Test 1b**  with Coursier-managed [bloop](https://github.com/scalacenter/bloop) (aka. `bloop.bat` + `.bloop.aux.exe`).

```
> %LOCALAPPDATA%\Coursier\data\bin\bloop server
Attempting a connection to the server...

>>>> same output as for test 1a <<<<<
```

### Scenario 2 : Java 11

```
> where python java
c:\opt\Python-3.10.4\python.exe
C:\opt\jdk-temurin-11.0.14.1_1\bin\java.exe
```
**Test 2a** with standalone executable [`bloop-x86_64-pc-win32.exe`](https://github.com/scalacenter/bloop/releases/tag/v1.4.13) : 

```
> c:\opt\bloop-1.4.13\bloop.exe server
Attempting a connection to the server...

>>>> same output as for test 1a <<<<<
```

**Test 2b**  with Coursier-managed [bloop](https://github.com/scalacenter/bloop) (aka. `bloop.bat` + `.bloop.aux.exe`).

```
> %LOCALAPPDATA%\Coursier\data\bin\bloop server
Attempting a connection to the server...

>>>> same output as for test 1a <<<<<
```

## Endnote

Version 1.3.4 (***from Martian Software, Inc.***) works fine : 

```
> c:\opt\bloop-1.3.4\bloop server
Defaulting on nailgun port 8212
There is no server running at port 8212
Starting the bloop server... this may take a few seconds
Running C:\opt\bloop-1.3.4\blp-server as a jar...
Shelling out with '['java', '-jar', 'C:\\opt\\bloop-1.3.4\\blp-server']' ...
Unable to load nailgun-version.properties.
NGServer [UNKNOWN] started on address localhost/127.0.0.1 port 8212
```

**Comment by tgodzik** [comment]
Thanks for reporting! Let's see if an update will help in this case https://github.com/scalacenter/bloop/pull/1722

**Comment by michelou** [comment]
@tgodzik What's the address for downloading a nightly builld ?!

**PS.** Other dependencies need to be updated, e.g. [`bsp4j`/`bsp4s`](https://mvnrepository.com/artifact/ch.epfl.scala/bsp4j/).

**Comment by tgodzik** [comment]
> PS. Other dependencies need to be updated, e.g. [bsp4j/bsp4s](https://mvnrepository.com/artifact/ch.epfl.scala/bsp4j/).

These ones are a bit problematic, but most likely are not related to the issue at hand.

> What's the address for downloading a nightly build ?!

We need to release a full native image in a release first to check this one out. I will do a release this week.

**Comment by tgodzik** [comment]
New release is out! Could you see if this is still an issue with 1.5.0?

**Comment by NirvanaNrv** [comment]
I do

**Comment by michelou** [comment]
@tgodzik Same issue with version 1.5.0 😒 
```
> coursier install bloop
https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
  No new update since 2022-03-30 18:39:24
https://repo1.maven.org/maven2/org/scala-lang/scala-library/maven-metadata.xml
  No new update since 2022-01-10 19:30:20
https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.13/maven-metadata.xml
  100.0% [##########] 2.0 KiB (15.9 KiB / s)
https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.13/maven-metadata.xml
  No new update since 2022-04-22 15:31:32
Wrote bloop
Warning: %LOCALAPPDATA%\coursier\data\bin is not in your PATH

> %LOCALAPPDATA%\coursier\data\bin\bloop.bat --version
No server running at 127.0.0.1:8212, let's fire one...
Resolving ch.epfl.scala:bloop-frontend_2.12:1.5.0...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315)
        at coursierapi.shaded.coursier.cache.shaded.dirs.ProjectDirectories.from(ProjectDirectories.java:298)
        [...]
        at coursierapi.Cache.create(Cache.java:22)
        [...]
        at bloop.bloopgun.Bloopgun.main(Bloopgun.scala)
Caused by: java.lang.RuntimeException: Could not find any viable Base64 encoder! (java.util.Base64 failed with: java.util.Base64$Encoder.encodeToString([B))
        at coursierapi.shaded.coursier.cache.shaded.dirs.Util.initBase64Encoding(Util.java:188)
        at coursierapi.shaded.coursier.cache.shaded.dirs.Util.toUTF16LEBase64(Util.java:170)
        at coursierapi.shaded.coursier.cache.shaded.dirs.Util.<clinit>(Util.java:49)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        ... 21 more
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder. This exception was synthesized during native image building from a call to java.lang.Class.forName(String) with constant arguments.
        at coursierapi.shaded.coursier.cache.shaded.dirs.Util.initBase64Encoding(Util.java:185)
        ... 25 more
```
From the error output the issue could have its origin in [`bloop-frontend_2.12`](https://mvnrepository.com/artifact/ch.epfl.scala/bloop-frontend).

Are there any changes in [`1.5.0-4-324c6c4c`](https://mvnrepository.com/artifact/ch.epfl.scala/bloop-frontend_2.12/1.5.0-4-324c6c4c) resp. [`1.5.0.5-2a743608`](https://mvnrepository.com/artifact/ch.epfl.scala/bloop-frontend_2.12/1.5.0-5-2a743608) relevant to this respect ?

**Comment by nartamonov** [comment]
I have the same problem with bloop 1.5.2 installed via coursier:

```
λ bloop server
Attempting a connection to the server...
Resolving ch.epfl.scala:bloop-frontend_2.12:1.5.2...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315)
        at coursierapi.shaded.coursier.cache.shaded.dirs.ProjectDirectories.from(ProjectDirectories.java:298)
        at coursierapi.shaded.coursier.paths.CoursierPaths.coursierDirectories(CoursierPaths.java:119)
        at coursierapi.shaded.coursier.paths.CoursierPaths.computeCacheDirectory(CoursierPaths.java:59)
        at coursierapi.shaded.coursier.paths.CoursierPaths.computeCacheDirectory(CoursierPaths.java:39)
        at coursierapi.shaded.coursier.paths.CoursierPaths.cacheDirectory(CoursierPaths.java:72)
        at coursierapi.shaded.coursier.paths.CachePath.defaultCacheDirectory(CachePath.java:105)
        at coursierapi.shaded.coursier.cache.CacheDefaults$.location$lzycompute(CacheDefaults.scala:16)
        at coursierapi.shaded.coursier.cache.CacheDefaults$.location(CacheDefaults.scala:16)
        at coursierapi.shaded.coursier.internal.api.ApiHelper$.defaultLocation(ApiHelper.scala:46)
        at coursierapi.shaded.coursier.internal.api.ApiHelper.defaultLocation(ApiHelper.scala)
        at coursierapi.Cache.<init>(Cache.java:17)
        at coursierapi.Cache.create(Cache.java:22)
        at coursierapi.Fetch.<init>(Fetch.java:23)
        at coursierapi.Fetch.create(Fetch.java:99)
        at bloop.bloopgun.core.DependencyResolution$.resolveWithErrors(DependencyResolution.scala:62)
        at bloop.bloopgun.core.ServerStatus$.resolveServer(ServerStatus.scala:16)
        at bloop.bloopgun.BloopgunCli.fireServer(Bloopgun.scala:364)
        at bloop.bloopgun.BloopgunCli.run(Bloopgun.scala:197)
        at bloop.bloopgun.Bloopgun$.main(Bloopgun.scala:623)
        at bloop.bloopgun.Bloopgun.main(Bloopgun.scala)
Caused by: java.lang.RuntimeException: Could not find any viable Base64 encoder! (java.util.Base64 failed with: java.util.Base64$Encoder.encodeToString([B))
        at coursierapi.shaded.coursier.cache.shaded.dirs.Util.initBase64Encoding(Util.java:188)
        at coursierapi.shaded.coursier.cache.shaded.dirs.Util.toUTF16LEBase64(Util.java:170)
        at coursierapi.shaded.coursier.cache.shaded.dirs.Util.<clinit>(Util.java:49)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        ... 20 more
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder. This exception was synthesized during native image building from a call to java.lang.Class.forName(String) with constant arguments.
        at coursierapi.shaded.coursier.cache.shaded.dirs.Util.initBase64Encoding(Util.java:185)
        ... 24 more
```

**Comment by nullptr7** [comment]
Same issue with v1.5.3

The issue is only when running bloop independently via cli i.e. `bloop server` (after downloading from coursier)

However, with VSCode (installing metals) it starts bloop successfully without any issues.

**Comment by tgodzik** [comment]
New release 1.5.4 is out, this should be fixed there, let me know if there are any further issues!
