### ISSUE TITLE
The `ExecutionContext` still has non-daemon threads when exiting

### ISSUE THREAD

**Issue by Duhemm** [scalacenter/bloop#176]
See in the benchmark logs for instance:

```
[info] <JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 24 seconds more...>
[info] Non-finished threads:
[info] Thread[pool-2-thread-4,5,main]
[info]   at sun.misc.Unsafe.park(Native Method)
[info]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[info]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
[info]   at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
[info]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
[info] Thread[DestroyJavaVM,5,main]
[info] Thread[pool-2-thread-8,5,main]
[info]   at sun.misc.Unsafe.park(Native Method)
[info]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[info]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
[info]   at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
[info]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
[info] Thread[pool-2-thread-5,5,main]
[info]   at sun.misc.Unsafe.park(Native Method)
[info]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[info]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
[info]   at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
[info]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
```

Related: #113

**Comment by jvican** [comment]
Is this still happening?

**Comment by jvican** [comment]
Closing until it's proven that this is an issue. I tried to reproduce and I couldn't. So assuming the best here.
