### ISSUE TITLE
I met these error message in 1.5.6 and 1.5.8

### ISSUE THREAD

**Issue by davidmlw** [scalacenter/bloop#2108]
The error message is not harmful but just annoying. It seems it would like to connect something but failed. The message is like this. Did anyone meet similar error message? And why is it? How to mute these messages?

```
Jul 08, 2023 11:45:12 AM zipkin2.reporter.AsyncReporter$BoundedAsyncReporter flush                              
WARNING: Spans were dropped due to exceptions. All subsequent errors will be logged at FINE level.              
Jul 08, 2023 11:45:12 AM zipkin2.reporter.AsyncReporter$BoundedAsyncReporter flush                              
WARNING: Dropped 1 spans due to ConnectException(Connection refused)                                            
java.net.ConnectException: Connection refused                                                                   
     at java.base/sun.nio.ch.Net.pollConnect(Native Method)                                                     
     at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)                                                   
     at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)                           
     at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)                                      
     at java.base/java.net.Socket.connect(Socket.java:633)                                                      
     at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)                                       
     at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)                                   
     at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)                                   
     at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:279)                                       
     at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:384)                                          
     at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:406)                                          
     at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)     
     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)        
     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)         
     at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)              
     at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)     
     at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)      
     at zipkin2.reporter.urlconnection.URLConnectionSender.send(URLConnectionSender.java:229)                   
     at zipkin2.reporter.urlconnection.URLConnectionSender$HttpPostCall.doExecute(URLConnectionSender.java:270) 
     at zipkin2.reporter.urlconnection.URLConnectionSender$HttpPostCall.doExecute(URLConnectionSender.java:262) 
     at zipkin2.Call$Base.execute(Call.java:391)                                                                
     at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:299)                       
     at zipkin2.reporter.AsyncReporter$Flusher.run(AsyncReporter.java:378)                                      
     at java.base/java.lang.Thread.run(Thread.java:833)                            
```

**Comment by tgodzik** [comment]
That's due to tracing, but it's not widely used, so I might need to remove it for the time being.
