### ISSUE TITLE
Support JDK 19

### ISSUE THREAD

**Issue by przemek-pokrywka** [scalacenter/bloop#2181]
Hello, when I try to run Bloop with JDK 19 (19.0.2, Java OpenJDK 64-Bit Server VM), I'm getting the following:

```
Exception in thread "main" java.lang.NoSuchFieldError: preferIPv6Address
	at java.base/sun.nio.ch.Net.initIDs(Native Method)
	at java.base/sun.nio.ch.Net.<clinit>(Net.java:807)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.unixBind(ServerSocketChannelImpl.java:328)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:299)
	at java.base/java.nio.channels.ServerSocketChannel.bind(ServerSocketChannel.java:224)
	at libdaemonjvm.internal.Java16SocketHandler$.server(Java16SocketHandler.scala:41)
	at libdaemonjvm.internal.SocketHandler$.server(SocketHandler.scala:20)
	at bloop.Bloop$.$anonfun$startServer$1(Bloop.scala:187)
	at scala.util.Either.map(Either.scala:353)
	at bloop.Bloop$.startServer(Bloop.scala:185)
	at bloop.Bloop$.$anonfun$main$4(Bloop.scala:95)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at libdaemonjvm.server.Lock$.unsafeWritePidAndSetup$1(Lock.scala:32)
	at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$3(Lock.scala:52)
	at scala.util.Either.flatMap(Either.scala:341)
	at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$2(Lock.scala:51)
	at scala.util.Either.flatMap(Either.scala:341)
	at libdaemonjvm.server.Lock$.unsafeCleanUpAndSetup$1(Lock.scala:50)
	at libdaemonjvm.server.Lock$.$anonfun$tryAcquire$9(Lock.scala:100)
	at libdaemonjvm.LockFiles.withLock(LockFiles.scala:37)
	at libdaemonjvm.server.Lock$.tryAcquire(Lock.scala:97)
	at bloop.Bloop$.loop$1(Bloop.scala:95)
	at bloop.Bloop$.main(Bloop.scala:113)
	at bloop.Bloop.main(Bloop.scala)
```

Due to this problem, the versions of Bloop and Scala-CLI from https://github.com/NixOS/nixpkgs don't work out of the box, one needs to override the JDK used.
I wonder if fixing it would be a quick thing or are there any serious blockers.

**Comment by tgodzik** [comment]
Thanks for reporting! Bloop seems to work correctly on JDK 19. Are you using it via Scala CLI? Though as far as I am aware that should work also.

**Comment by przemek-pokrywka** [comment]
Yes, through Scala CLI. Though I can only reproduce the issue on my local setup (the issue does not occur on a fresh Ubuntu install) so it must have been my setup, sorry for the confusion! I'm closing the ticket now.
