### ISSUE TITLE
installation on mac fails

### ISSUE THREAD

**Issue by mh-trimble** [scalacenter/bloop#2265]
Installation on m1 mac fails

```
cs install bloop --only-prebuilt=true --verbose
Using install directory /Users/martinheuschober/Library/Application Support/Coursier/bin
Found app bloop in channel io.get-coursier:apps
Exception in thread "main" java.lang.Exception: coursier.install.AppArtifacts$ScalaDependenciesNotFound: Can't find a scala version suffix for ch.epfl.scala::bloopgun:latest.stable (likely a non existing module or version)
        at coursier.install.AppDescriptor.candidateMainVersions(AppDescriptor.scala:269)
        at coursier.install.internal.PrebuiltApp$.mainVersionsIterator$1(PrebuiltApp.scala:155)
        at coursier.install.internal.PrebuiltApp$.patternArtifacts$1(PrebuiltApp.scala:188)
        at coursier.install.internal.PrebuiltApp$.$anonfun$candidatePrebuiltArtifacts$11(PrebuiltApp.scala:210)
        at scala.Option.map(Option.scala:230)
        at coursier.install.internal.PrebuiltApp$.candidatePrebuiltArtifacts(PrebuiltApp.scala:210)
        at coursier.install.internal.PrebuiltApp$.get(PrebuiltApp.scala:107)
        at coursier.install.InstallDir.update$1(InstallDir.scala:258)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:408)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:407)
        at coursier.install.Updatable$.get$1(Updatable.scala:61)
        at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
        at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:73)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:93)
        at coursier.install.Updatable$.writing(Updatable.scala:106)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:407)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
        at coursier.cli.install.Install$.$anonfun$run$7(Install.scala:128)
        at coursier.cli.install.Install$.$anonfun$run$7$adapted(Install.scala:115)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at coursier.cli.install.Install$.run(Install.scala:115)
        at coursier.cli.install.Install$.run(Install.scala:23)
        at caseapp.core.app.CaseApp.main(CaseApp.scala:157)
        at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:161)
        at coursier.cli.Coursier$.main(Coursier.scala:118)
        at coursier.cli.Coursier.main(Coursier.scala)
Caused by: coursier.install.AppArtifacts$ScalaDependenciesNotFound: Can't find a scala version suffix for ch.epfl.scala::bloopgun:latest.stable (likely a non existing module or version)
        at coursier.install.AppDescriptor.$anonfun$processDependencies$9(AppDescriptor.scala:231)
        at scala.Option.toRight(Option.scala:485)
        at coursier.install.AppDescriptor.processDependencies(AppDescriptor.scala:231)
        at coursier.install.AppDescriptor.candidateMainVersions(AppDescriptor.scala:267)
        ... 25 more
```

**Comment by tgodzik** [comment]
Thanks for reporting! Does it work without prebuilt parameter? We don't publish native image for m1

**Comment by tgodzik** [comment]
Ach, I think an alternative might be to use jar based launcher. I think it's under bloop-jvm

**Comment by mh-trimble** [comment]
so the prebuilt param did not work - how can I try to launch bloop-jvm?

**Comment by tgodzik** [comment]
> so the prebuilt param did not work (with or without) - how can I try to launch bloop-jvm?

`cs install bloop-jvm` should work

**Comment by mh-trimble** [comment]
yepp it does - thanks
