### ISSUE TITLE
Cannot load bloop sbt bulid

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/bloop#252]
```
gui@nixos-bob:~/bloop% sbt                                                ~/bloop
[info] Loading settings from build.sbt ...
[info] Loading project definition from /home/gui/bloop/project
[info] Loading settings from build.sbt ...
[error] java.lang.RuntimeException: No project 'compilation' in 'file:///home/gui/bloop/benchmark-bridge/'.
[error] Valid project IDs: benchmark-bridge
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at sbt.internal.Load$.$anonfun$checkAll$3(Load.scala:595)
[error]         at sbt.internal.Load$.$anonfun$checkAll$3$adapted(Load.scala:589)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at sbt.internal.Load$.$anonfun$checkAll$2(Load.scala:589)
[error]         at sbt.internal.Load$.$anonfun$checkAll$2$adapted(Load.scala:589)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error]         at scala.collection.immutable.Map$Map2.foreach(Map.scala:146)
[error]         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error]         at sbt.internal.Load$.checkAll(Load.scala:589)
[error]         at sbt.internal.Load$.loadURI(Load.scala:486)
[error]         at sbt.internal.Load$.load(Load.scala:464)
[error]         at sbt.internal.Load$.$anonfun$apply$1(Load.scala:253)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.apply(Load.scala:253)
[error]         at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error]         at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:707)
[error]         at sbt.BuiltinCommands$.doLoadProject(Main.scala:707)
[error]         at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:680)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:134)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error]         at sbt.State$$anon$1.process(State.scala:248)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:136)
[error]         at sbt.MainLoop$.run(MainLoop.scala:129)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error]         at sbt.StandardMain$.runManaged(Main.scala:113)
[error]         at sbt.xMain.run(Main.scala:76)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error]         at xsbt.boot.Boot$.main(Boot.scala:17)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] No project 'compilation' in 'file:///home/gui/bloop/benchmark-bridge/'.
[error] Valid project IDs: benchmark-bridge
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by MasseGuillaume** [comment]
`git clone --recursive git@github.com:scalacenter/bloop.git`

**Comment by stewSquared** [comment]
Easy to miss. Thank you.
Perhaps that should be more explicit in the docs.
