### ISSUE TITLE
NullPointerException running bloop projects

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#262]
* Clone https://github.com/scalameta/scalameta 
* sbt installBloop
* bloop projects

```
java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.nio.file.Paths.get(Paths.java:84)
	at bloop.Project$.toPath$1(Project.scala:76)
	at bloop.Project$.fromProperties(Project.scala:101)
	at bloop.Project$.fromFile(Project.scala:71)
	at bloop.Project$.$anonfun$fromDir$2(Project.scala:60)
	at bloop.Project$.$anonfun$fromDir$2$adapted(Project.scala:60)
	at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:656)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
	at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:647)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:166)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Suppressed: java.lang.NullPointerException
		... 27 more
		Suppressed: java.lang.NullPointerException
			... 27 more
	Suppressed: java.lang.NullPointerException
		at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
		at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
		at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
		at java.nio.file.Paths.get(Paths.java:84)
		at bloop.Project$.toPath$1(Project.scala:76)
		at bloop.Project$.fromProperties(Project.scala:101)
		at bloop.Project$.fromFile(Project.scala:71)
		at bloop.Project$.$anonfun$fromDir$2(Project.scala:60)
		at bloop.Project$.$anonfun$fromDir$2$adapted(Project.scala:60)
		at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:656)
		at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
		at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
		at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
		at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
		at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
		at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:647)
		at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:156)
		... 10 more
```

**Comment by olafurpg** [comment]
Nevermind, `rm -rf .bloop-config` and restart fixed the problem. Seems I had some legacy config files lying around that cause problems. installBloop should probably clean up old files, and bloop should probably add more graceful error handling while decoding config files.
