### ISSUE TITLE
NoSuchMethodError running `bloop about`

### ISSUE THREAD

**Issue by avdv** [scalacenter/bloop#463]
Hi.

On my Linux box, I installed bloop using `curl -L https://github.com/scalacenter/bloop/releases/download/v1.0.0-M9/install.py | python`

I have started the server with `~/.bloop/bloop server` in an xterm.

Trying to run `bloop about` results in an exception:

```
~/.bloop/bloop about
May 02, 2018 3:59:22 PM com.martiansoftware.nailgun.NGSession run
INFO: Server unexpectedly exited with unhandled exception
java.lang.NoSuchMethodError: io.github.soc.directories.ProjectDirectories.fromProjectName(Ljava/lang/String;)Lio/github/soc/directories/ProjectDirectories;
	at bloop.io.Paths$.<init>(Paths.scala:19)
	at bloop.io.Paths$.<clinit>(Paths.scala)
	at bloop.Project$.loadAllFiles(Project.scala:44)
	at bloop.Project$.$anonfun$lazyLoadFromDir$1(Project.scala:56)
	at bloop.io.Timer$.timed(Timer.scala:9)
	at bloop.Project$.lazyLoadFromDir(Project.scala:54)
	at bloop.engine.State$.$anonfun$loadActiveStateFor$1(State.scala:118)
	at bloop.engine.State$.$anonfun$loadActiveStateFor$1$adapted(State.scala:117)
	at bloop.engine.caches.StateCache.computeAndSave$1(StateCache.scala:44)
	at bloop.engine.caches.StateCache.addIfMissing(StateCache.scala:54)
	at bloop.engine.State$.loadActiveStateFor(State.scala:117)
	at bloop.Cli$.run(Cli.scala:225)
	at bloop.Cli$.nailMain(Cli.scala:52)
	at bloop.Cli.nailMain(Cli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:345)

java.lang.NoSuchMethodError: io.github.soc.directories.ProjectDirectories.fromProjectName(Ljava/lang/String;)Lio/github/soc/directories/ProjectDirectories;
	at bloop.io.Paths$.<init>(Paths.scala:19)
	at bloop.io.Paths$.<clinit>(Paths.scala)
	at bloop.Project$.loadAllFiles(Project.scala:44)
	at bloop.Project$.$anonfun$lazyLoadFromDir$1(Project.scala:56)
	at bloop.io.Timer$.timed(Timer.scala:9)
	at bloop.Project$.lazyLoadFromDir(Project.scala:54)
	at bloop.engine.State$.$anonfun$loadActiveStateFor$1(State.scala:118)
	at bloop.engine.State$.$anonfun$loadActiveStateFor$1$adapted(State.scala:117)
	at bloop.engine.caches.StateCache.computeAndSave$1(StateCache.scala:44)
	at bloop.engine.caches.StateCache.addIfMissing(StateCache.scala:54)
	at bloop.engine.State$.loadActiveStateFor(State.scala:117)
	at bloop.Cli$.run(Cli.scala:225)
	at bloop.Cli$.nailMain(Cli.scala:52)
	at bloop.Cli.nailMain(Cli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:345)
```

Seems that this method has been removed from soc/directories-jvm in version 7, commit soc/directories-jvm@4305e70a93ab9acc6256b10f7f3087e9902d671f

Looking into the `blp-coursier` jar, there are class files in `io/github/soc/directories` which probably interfere with the files in `jars/directories-5.jar`.

**Comment by avdv** [comment]
I could fix this with manually downloading https://github.com/coursier/coursier/raw/06796458b576e9bd8a49f8b121c0048b257bc08f/coursier to `~/.bloop/blp-coursier` (coursier v1.1.0-M1 is broken too).

**Comment by jvican** [comment]
I just tried it locally and that fixes it, but I'd prefer to upgrade the `directories` version instead. We're behind anyway :smile:.

**Comment by avdv** [comment]
Hi Jorge, thank you for your reply. +1 for upgrading `directories`!
