### ISSUE TITLE
Bloop breaks scalafmt

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [scalacenter/bloop#490]
Hello Bloop team,

I had filed an [issue](https://github.com/scalacenter/bloop/issues/453) earlier about not being able to use bloop and `scalafmt` together. The issue was closed with an update saying that the fix will be available in the next release. I tried to upgrade to bloop 1.0.0-M10 today but I got this new error

```scala
[error] Caused by: java.lang.ClassNotFoundException: metaconfig.HasFields
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[error] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at org.scalafmt.sbt.ScalafmtPlugin$.<init>(ScalafmtPlugin.scala:49)
[error] 	at org.scalafmt.sbt.ScalafmtPlugin$.<clinit>(ScalafmtPlugin.scala)
[error] 	at java.lang.Class.forName0(Native Method)
```

```scala
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.5.1")
```
```scala
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.0.0-M10")
```

**Comment by Duhemm** [comment]
It looks like both bloop and scalafmt pull in binary incompatible versions of metaconfig. This should be fixed by using the latest pre-release of scalafmt, which updates metaconfig: ![alt text](https://api.bintray.com/packages/scalameta/maven/scalafmt-cli/images/download.svg "Logo Title Text 1")

**Comment by Duhemm** [comment]
Olaf says it's his fault!
