### ISSUE TITLE
Build fails because of missing 'sourceDir' 

### ISSUE THREAD

**Issue by vilu** [scalacenter/bloop#508]
Command: `mvn ch.epfl.scala:maven-bloop_2.12:1.0.0-M10+28-ce2c8158:bloopInstall -X`

Error: 
```
[ERROR] Failed to execute goal ch.epfl.scala:maven-bloop_2.12:1.0.0-M10+28-ce2c8158:bloopInstall (default-cli) on project ${PROJECT_NAME}: Unable to parse configuration of mojo ch.epfl.scala:maven-bloop_2.12:1.0.0-M10+28-ce2c8158:bloopInstall for parameter sourceDir: Cannot find 'sourceDir' in class bloop.integrations.maven.BloopMojo -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal ch.epfl.scala:maven-bloop_2.12:1.0.0-M10+28-ce2c8158:bloopInstall (default-cli) on project ${PROJECT_NAME}: Unable to parse configuration of mojo ch.epfl.scala:maven-bloop_2.12:1.0.0-M10+28-ce2c8158:bloopInstall for parameter sourceDir: Cannot find 'sourceDir' in class bloop.integrations.maven.BloopMojo
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse configuration of mojo ch.epfl.scala:maven-bloop_2.12:1.0.0-M10+28-ce2c8158:bloopInstall for parameter sourceDir: Cannot find 'sourceDir' in class bloop.integrations.maven.BloopMojo
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:664)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:596)
	at bloop.integrations.maven.MojoImplementation$.initializeMojo(MojoImplementation.scala:28)
	at bloop.integrations.maven.MojoImplementation.initializeMojo(MojoImplementation.scala)
	at bloop.integrations.maven.BloopMojo.execute(BloopMojo.java:61)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot find 'sourceDir' in class bloop.integrations.maven.BloopMojo
	at org.eclipse.sisu.plexus.CompositeBeanHelper.setProperty(CompositeBeanHelper.java:252)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:101)
	at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:34)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:634)
```

**Comment by jvican** [comment]
@lefou Do you have any idea if your recent changes fixed this? It seems to happen because it does `bloopInstall` in a project that is not Scala and does not set up `scala-maven-plugin`.

**Comment by vilu** [comment]
Can I help with this issue in any way? I just did minor debugging by running this plugin in debug mode but I didn't find the cause. If you gave me a few pointers on normal debug flow for this kind of issues I would give it a shot myself.

**Comment by jvican** [comment]
@vilu I don't understand what's happening here but let's look into it.
  
1. What's the maven version you use? Upgrade to the latest one you can.
2. Have you confirmed you use `scala-maven-plugin`? What version? Upgrade to the latest one you can.
3. Can you grep in your repository for instances of `sourceDir`? It's weird that this field makes the plugin fail because the plugin cannot be configured with `sourceDir`. For example, this is the file [describing the maven plugin descriptor](https://gist.github.com/jvican/d20d925e69b03aeef44f1a78ce1ee22f) and specifies all of its inputs.

**Comment by jvican** [comment]
@vilu When you've got some time, your input here would be much appreciated :wink:.

**Comment by jvican** [comment]
Closing for inactivity.
