### ISSUE TITLE
Error running set bloopInstall: java.lang.IncompatibleClassChangeError: Implementing class

### ISSUE THREAD

**Issue by manonthegithub** [scalacenter/bloop#626]
Running `sbt bloopInstall` I get the following exception:
```
java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:14)
	at sbt.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:20)
	at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
	at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream.foreach(Stream.scala:548)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.TraversableLike$class.to(TraversableLike.scala:629)
	at scala.collection.AbstractTraversable.to(Traversable.scala:105)
	at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:257)
	at scala.collection.AbstractTraversable.toList(Traversable.scala:105)
	at scala.collection.immutable.List.$plus$plus(List.scala:193)
	at sbt.PluginDiscovery$.discoverAll(PluginDiscovery.scala:39)
	at bloop.integrations.sbt.BloopDefaults$$anonfun$computeSbtMetadata$1$$anonfun$apply$28.apply(SbtBloop.scala:592)
	at bloop.integrations.sbt.BloopDefaults$$anonfun$computeSbtMetadata$1$$anonfun$apply$28.apply(SbtBloop.scala:582)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (compile:bloopGenerate) java.lang.IncompatibleClassChangeError: Implementing class
[error] Total time: 10 s, completed Aug 15, 2018 2:57:36 PM
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
```
There is no more meaningful output so I do not know how to make the description of the issue better.
`sbt.version=0.13.17`
`bloop version = 1.0.0`
`bloop set-plugin = 1.0.0`
The bloop sbt-plugin is added as global plugin in the ~/.sbt/plugins/build.sbt

**Comment by manonthegithub** [comment]
I've found out that if you set the `bloop-sbt` as project's plugin no exception occurs and sbt bloopInstall works fine.
