### ISSUE TITLE
Stackoverflow while compile shapeless lazy macro using graalvm ce 1.0.0-rc10

### ISSUE THREAD

**Issue by jilen** [scalacenter/bloop#750]
```
java.lang.StackOverflowError
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:114)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:790)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:728)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:123)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:790)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:728)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:123)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:790)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.applyToSymbolInfo(TypeMaps.scala:232)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.loop$1(TypeMaps.scala:242)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.firstChangedSymbol(TypeMaps.scala:246)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:259)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.$anonfun$mapOver$1(TypeMaps.scala:137)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:216)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:790)
	at scala.reflect.internal.Types$Type.subst(Types.scala:744)
	at scala.reflect.internal.Types$Type.instantiateTypeParams(Types.scala:491)
	at scala.tools.nsc.typechecker.Infer$Inferencer.restpeInst$1(Infer.scala:370)
	at scala.tools.nsc.typechecker.Infer$Inferencer.conforms$1(Infer.scala:371)
	at scala.tools.nsc.typechecker.Infer$Inferencer.exprTypeArgs(Infer.scala:381)
	at scala.tools.nsc.typechecker.Infer$Inferencer.inferExprInstance(Infer.scala:903)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:852)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1239)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1236)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1(Implicits.scala:768)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit0(Implicits.scala:705)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$typedImplicit(Implicits.scala:529)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:1028)

```

[Full stacktrace](https://gist.github.com/jilen/78a2500cf4e17604042b448333f2da4d)

Note that sbt could compile it with no error while using graalvm

**Comment by olafurpg** [comment]
The difference between sbt and bloop here is caused by JVM properties. How does one increase `Xss` for the bloop server @jvican ?

**Comment by jilen** [comment]
Same question as @olafurpg here!

**Comment by jilen** [comment]
It could be set in `install.py`, by adding `--java-opt` in coursier bootstrap section. Just in case someone suffer from the same error.

**Comment by jilen** [comment]
I found enable `metals` cause such error on graalvm

**Comment by olafurpg** [comment]
Thanks for reporting @jilen I think it would be a good idea to update the docs to use a larger stack size by default.

**Comment by olafurpg** [comment]
@jilen the docs for building metals bootstrap scripts already use `--java-opt -Xss4m` (https://scalameta.org/metals/docs/editors/vim.html#installing-the-plugin), what stack size did you need to compile your project?

**Comment by jilen** [comment]
@olafurpg  I set it to 256m, the error goes away if I not run `metalsEnable` while generate bloop config.

**Comment by jilen** [comment]
@olafurpg Yes, I set it to 256m and still got stackoverflow. but it only crash graalvm, eclipse openj9 works just fine.

**Comment by jvican** [comment]
@jilen I will add a change in 1.2.0 so that anything in `.jvmopts` gets picked up by bloop when it starts up. That will simplify passing arguments to the server and will allow all servers that are ever started use the same settings (important for reproducibility and debugging).

**Comment by jilen** [comment]
@jvican That would be great! Thanks
