### ISSUE TITLE
Broken installation via `brew`

### ISSUE THREAD

**Issue by danbim** [scalacenter/bloop#757]
Tried to install bloop via `brew`, seems to fail (actually) starting bloop. Below is an excerpt of my attempts:

```
$ brew install scalacenter/bloop/bloop

$ brew services start scalacenter/bloop/bloop

$ brew services list
[...]
bloop      started username /Users/username/Library/LaunchAgents/homebrew.mxcl.bloop.plist
[...]

$ bloop
Could not connect to server 127.0.0.1:8212

Have you forgotten to start bloop's server? Run it with `bloop server`.
Check our usage instructions in https://scalacenter.github.io/bloop/

$ bloop server
Error: Invalid or corrupt jarfile /usr/local/bin/blp-server
Traceback (most recent call last):
  File "/usr/local/bin/bloop", line 1084, in <module>
    main()
  File "/usr/local/bin/bloop", line 1047, in main
    except CallProcessError as e2:
NameError: global name 'CallProcessError' is not defined

$ ls -la /usr/local/bin/blp-server
lrwxr-xr-x  1 username  admin  36 Dec 12 09:01 /usr/local/bin/blp-server -> ../Cellar/bloop/1.1.1/bin/blp-server

$ /usr/local/Cellar/bloop/1.1.1/bin/blp-server
Error: Could not find or load main class rjar

$ cat /usr/local/Cellar/bloop/1.1.1/bin/blp-server
#!/usr/bin/env sh

BASE_BIN_DIR=$(dirname "$0")
COURSIER_BIN="$BASE_BIN_DIR/blp-coursier"
/usr/libexec/java_home -v 1.8 -F -R --exec java        rjar "$COURSIER_BIN" launch ch.epfl.scala:bloop-frontend_2.12:1.1.1       -r bintray:scalameta/maven       -r bintray:scalacenter/releases       -r https://oss.sonatype.org/content/repositories/staging       --main bloop.Server
```

**Comment by jvican** [comment]
This is fixed in master. I'm cutting a release today. I apologize for the inconvenience.

**Comment by jvican** [comment]
Also, see https://github.com/scalacenter/bloop/issues/753 for a workaround

**Comment by danbim** [comment]
Awesome! Thank you for the quick response :)
