### ISSUE TITLE
Failure to set proxy variables globally

### ISSUE THREAD

**Issue by entangled90** [scalacenter/bloop#802]
I have a problem with the proxy in bloop.
I would use gitter, but being behind a proxy doesn't help.
The server blows up when trying to compile a project.
The stacktrace is the following:
```
INFO: Nail raised unhandled exception
scala.MatchError: Some(ProxySettings(localhost,3128,Some(local|*.local|169.254/16|*.169.254/16))) (of class scala.Some)
	at bloop.util.ProxySetup$.$anonfun$updateProxySettings$2(ProxySetup.scala:116)
	at bloop.util.ProxySetup$.$anonfun$updateProxySettings$2$adapted(ProxySetup.scala:114)
	at scala.Option.foreach(Option.scala:274)
	at bloop.util.ProxySetup$.$anonfun$updateProxySettings$1(ProxySetup.scala:114)
	at bloop.util.ProxySetup$.$anonfun$updateProxySettings$1$adapted(ProxySetup.scala:111)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at bloop.util.ProxySetup$.updateProxySettings(ProxySetup.scala:111)
	at bloop.Cli$.run(Cli.scala:272)
	at bloop.Cli$.run(Cli.scala:231)
	at bloop.Cli$.nailMain(Cli.scala:78)
	at bloop.Cli.nailMain(Cli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:280)
```

If someone can give me a little hint I can do a PR.

Thanks for your effort!

**Comment by jvican** [comment]
Hey @entangled90, this is a bug. I'm fixing it soon, will give you a release version you can install and use when it's merged in master.

**Comment by jvican** [comment]
Fix for this will be available in coming release

**Comment by entangled90** [comment]
Thanks for the fix!
Is there a release that can be used in the meantime?


Thank you for the support.

**Comment by jvican** [comment]
@entangled90 I'll keep you posted when I publish something that can be used by people, latest master is currently a little bit unstable to my personal taste.
