### ISSUE TITLE
"No such file or directory" when switching branches while using `bloop <cmd> --watch`

### ISSUE THREAD

**Issue by jrudolph** [scalacenter/bloop#922]
Happening with bloop 1.2.5

```
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at sbt.internal.inc.ClassFileManager$TransactionalClassFileManager.move(ClassFileManager.scala:112)
	at sbt.internal.inc.ClassFileManager$TransactionalClassFileManager.$anonfun$delete$4(ClassFileManager.scala:88)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at sbt.internal.inc.ClassFileManager$TransactionalClassFileManager.delete(ClassFileManager.scala:87)
	at xsbti.compile.WrappedClassFileManager.delete(WrappedClassFileManager.java:43)
	at sbt.internal.inc.IncrementalCommon$.pruneClassFilesOfInvalidations(IncrementalCommon.scala:732)
	at sbt.internal.inc.bloop.internal.BloopNameHashing.recompileClasses(BloopNameHashing.scala:135)
	at sbt.internal.inc.bloop.internal.BloopNameHashing.entrypoint(BloopNameHashing.scala:71)
	at sbt.internal.inc.bloop.internal.BloopNameHashing.$anonfun$entrypoint$1(BloopNameHashing.scala:120)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:176)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at monix.execution.internal.forkJoin.AdaptedForkJoinTask.exec(AdaptedForkJoinTask.scala:27)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by jvican** [comment]
Yup! This is expected, `v1.3.0-RC1` fixes this, thanks for reporting nonetheless! :smile:
