### ISSUE TITLE
Clean puts bloop in bad state

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#94]
Using bloop to compile bloop

```
bloop compile -p frontend # OK
bloop clean -p backend # OK
bloop compile -p frontend
Nov 30, 2017 1:08:08 PM com.martiansoftware.nailgun.NGSession run
INFO: Server unexpectedly exited with unhandled exception
java.util.NoSuchElementException: key not found: frontend
	at scala.collection.MapLike.default(MapLike.scala:232)
	at scala.collection.MapLike.default$(MapLike.scala:231)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike.apply(MapLike.scala:141)
	at scala.collection.MapLike.apply$(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at bloop.engine.Interpreter$.$anonfun$compile$1(Interpreter.scala:105)
```
It seems the exception gets caught by nailgun

**Comment by jvican** [comment]
Is this done @Duhemm ?

**Comment by Duhemm** [comment]
Didn't have time yet. First thing tomorrow though. Or just re-assign if you want to have a stab at it!
