### ISSUE TITLE
Bloop fails to run as a service on Ubuntu

### ISSUE THREAD

**Issue by ioreskovic** [scalacenter/bloop#943]
I installed and configured Bloop as per instructions.
I wanted to run it as a service, so I followed instructions there as well.
However, when I attempted to start the service, it failed.

```log
   ioreskovic@RA-149-LTU   ~  journalctl --user-unit bloop
Jun 26 14:42:28 RA-149-LTU systemd[2474]: Started Bloop Scala build server.
Jun 26 14:42:28 RA-149-LTU bloop[32598]: Defaulting on nailgun port 8212
Jun 26 14:42:28 RA-149-LTU bloop[32598]: There is no server running at port 8212
Jun 26 14:42:28 RA-149-LTU bloop[32598]: Starting the bloop server... this may take a few seconds
Jun 26 14:42:28 RA-149-LTU bloop[32598]: Running /home/ioreskovic/.bloop/blp-server as a jar...
Jun 26 14:42:28 RA-149-LTU bloop[32598]: Shelling out with '['java', '-jar', '/home/ioreskovic/.bloop/blp-server']' ...
Jun 26 14:42:28 RA-149-LTU bloop[32598]: Traceback (most recent call last):
Jun 26 14:42:28 RA-149-LTU bloop[32598]:   File "/home/ioreskovic/.bloop/bloop", line 1206, in <module>
Jun 26 14:42:28 RA-149-LTU bloop[32598]:     main()
Jun 26 14:42:28 RA-149-LTU bloop[32598]:   File "/home/ioreskovic/.bloop/bloop", line 1120, in main
Jun 26 14:42:28 RA-149-LTU bloop[32598]:     check_call(java_cmd)
Jun 26 14:42:28 RA-149-LTU bloop[32598]:   File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
Jun 26 14:42:28 RA-149-LTU bloop[32598]:     retcode = call(*popenargs, **kwargs)
Jun 26 14:42:28 RA-149-LTU bloop[32598]:   File "/usr/lib/python2.7/subprocess.py", line 172, in call
Jun 26 14:42:28 RA-149-LTU bloop[32598]:     return Popen(*popenargs, **kwargs).wait()
Jun 26 14:42:28 RA-149-LTU bloop[32598]:   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
Jun 26 14:42:28 RA-149-LTU bloop[32598]:     errread, errwrite)
Jun 26 14:42:28 RA-149-LTU bloop[32598]:   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
Jun 26 14:42:28 RA-149-LTU bloop[32598]:     raise child_exception
Jun 26 14:42:28 RA-149-LTU bloop[32598]: OSError: [Errno 2] No such file or directory
Jun 26 14:42:28 RA-149-LTU systemd[2474]: bloop.service: Main process exited, code=exited, status=1/FAILURE
Jun 26 14:42:28 RA-149-LTU systemd[2474]: bloop.service: Failed with result 'exit-code'.
```

When ran manually with that command
```log
   ioreskovic@RA-149-LTU   ~  java -jar /home/ioreskovic/.bloop/blp-server                                                                                          15:01:01 CEST Wednesday, 26 June 2019  
Unable to load nailgun-version.properties.
NGServer [UNKNOWN] started on address localhost/127.0.0.1 port 8212.
```

**Comment by jvican** [comment]
That's quite surprising, it's as if `java` is not accessible from services run by systemd. How did you install `java`? Have you made sure it's in the classpath and configured such as Java applications can run as services? @ioreskovic

**Comment by ioreskovic** [comment]
@jvican Java is installed via [SDKMAN!](https://sdkman.io/).
I have not tried to run any other java apps as services.

```log
   ioreskovic@RA-149-LTU   ~  which java                                                                                                                            22:58:49 CEST Wednesday, 26 June 2019  
/home/ioreskovic/.sdkman/candidates/java/current/bin/java
```

**Comment by jvican** [comment]
Thanks for reporting!

I'd look into why `java` is not detected in your systemd services. Even if `/usr/bin/java` doesn't exist, `java` should succeed if the `PATH` is correctly set up (which I suspect it isn't). There must be other SDKMAN users having the same issue out there... Please, if you find a workaround, feel free to post it in a new message.
  
I'm closing the ticket given that there's nothing we can do on the bloop side to make your service work, it's an installation issue.

**Comment by ioreskovic** [comment]
Java seems to be here

```log
   ioreskovic@RA-149-LTU   /usr/bin    echo $PATH                                                                                                                 23:10:26 CEST Wednesday, 26 June 2019  
/home/ioreskovic/.sdkman/candidates/scala/current/bin:/home/ioreskovic/.sdkman/candidates/sbt/current/bin:/home/ioreskovic/.sdkman/candidates/maven/current/bin:/home/ioreskovic/.sdkman/candidates/java/current/bin:/home/ioreskovic/.sdkman/candidates/gradle/current/bin:/home/ioreskovic/.bloop:/home/ioreskovic/.local/bin:/home/ioreskovic/.bloop:/home/ioreskovic/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by jvican** [comment]
You need to check that it is still there when systemd runs `java`. If that trace in the python script fails is because `java` isn't in the `PATH` of the systemd service

**Comment by ioreskovic** [comment]
@jvican I found a workaround.

This is what `systemd` sees under `PATH`:
```log
Jun 27 16:08:01 RA-149-LTU bloop[3961]: /home/ioreskovic/.bloop:/home/ioreskovic/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

I symlinked `java` to `/usr/bin`
```log
   ioreskovic@RA-149-LTU   ~  sudo ln -s /home/ioreskovic/.sdkman/candidates/java/current/bin/java /usr/bin/java                                                     16:15:53 CEST Thursday, 27 June 2019  
```
Tried to start it again, and it works!
```log
   ioreskovic@RA-149-LTU   ~  systemctl --user start bloop                                                                                                           16:15:25 CEST Thursday, 27 June 2019  
   ioreskovic@RA-149-LTU   ~  systemctl --user status bloop                                                                                                          16:15:35 CEST Thursday, 27 June 2019  
● bloop.service - Bloop Scala build server
   Loaded: loaded (/home/ioreskovic/.bloop/systemd/bloop.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-06-27 16:15:35 CEST; 3s ago
 Main PID: 7592 (python)
   CGroup: /user.slice/user-1001.slice/user@1001.service/bloop.service
           ├─7592 python /home/ioreskovic/.bloop/bloop server
           └─7633 java -jar /home/ioreskovic/.bloop/blp-server

Jun 27 16:15:35 RA-149-LTU systemd[2022]: Started Bloop Scala build server.
Jun 27 16:15:36 RA-149-LTU bloop[7592]: Unable to load nailgun-version.properties.
Jun 27 16:15:36 RA-149-LTU bloop[7592]: NGServer [UNKNOWN] started on address localhost/127.0.0.1 port 8212.
   ioreskovic@RA-149-LTU   ~  bloop about                                                                                                                            16:15:39 CEST Thursday, 27 June 2019  
bloop v1.3.2

Using Scala v2.12.8 and Zinc v1.3.0-M4+22-4704d479
Running on Java v1.8.0_201 (/home/ioreskovic/.sdkman/candidates/java/8.0.201-zulu/jre)
Maintained by the Scala Center (Martin Duhem, Jorge Vicente Cantero)
   ioreskovic@RA-149-LTU   ~                                                                                                                                         16:15:53 CEST Thursday, 27 June 2019  
```
