### ISSUE TITLE
Bloop Exception `java.io.EOFException` (Arch Linux)

### ISSUE THREAD

**Issue by isomarcte** [scalacenter/bloop#973]
I'm getting this error consistently when running bloop. I don't know if it is related or not, but after using the system for a while bloop commands just seem to time out. They neither fail, complete, nor give any output. I don't think it has been working for about a month, but I've only just recently looked into it a bit.

```
Jul 20 12:15:50 smaug systemd[598]: Started Bloop Scala build server.
Jul 20 12:15:51 smaug bloop[607]: Unable to load nailgun-version.properties.
Jul 20 12:15:51 smaug bloop[607]: NGServer [UNKNOWN] started on address localhost/127.0.0.1 port 8212.
Jul 20 12:19:33 smaug bloop[607]: [W] Internal error in session
Jul 20 12:19:33 smaug bloop[607]: java.io.EOFException
Jul 20 12:19:33 smaug bloop[607]:         at java.io.DataInputStream.readInt(DataInputStream.java:392)
Jul 20 12:19:33 smaug bloop[607]:         at com.martiansoftware.nailgun.NGCommunicator.readCommandContext(NGCommunicator.java:140)
Jul 20 12:19:33 smaug bloop[607]:         at com.martiansoftware.nailgun.NGSession.run(NGSession.java:197)
```

### OS ###

* Linux (Arch linux)

```shell
[SSH] [smaug]~ λ > cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

```shell
[SSH] [smaug]~ λ > uname -a
Linux smaug 5.2.1-arch1-1-ARCH #1 SMP PREEMPT Sun Jul 14 14:52:52 UTC 2019 x86_64 GNU/Linux
```

### Java Information ###

```shell
[SSH] [smaug]~ λ > archlinux-java get
java-8-openjdk
```

### Bloop Information ###

```shell
[SSH] [smaug]~ λ > pacman -Qi bloop
Name            : bloop
Version         : 1.3.2-1
Description     : Bloop gives you fast edit/compile/test workflows for Scala.
Architecture    : any
URL             : https://scalacenter.github.io/bloop/
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : scala  python
Optional Deps   : None
Required By     : None
Optional For    : metals
Conflicts With  : None
Replaces        : None
Installed Size  : 115.00 KiB
Packager        : Unknown Packager
Build Date      : Mon 10 Jun 2019 10:04:56 AM MDT
Install Date    : Mon 10 Jun 2019 10:05:06 AM MDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

**Comment by jvican** [comment]
Thank you for reporting this issue with such great detail! This issue is fine and it doesn't affect in any way the behavior of the server, it happens to be an implementation detail from our nailgun combo (nailgun python client talking to Java nailgun server). I think that whenever we roll own our own client with https://github.com/jvican/snailgun, this issue should disappear, otherwise it'll require a change upstream.
